//! `patchlevel.h` port — upstream zsh patch-level identifier.
//!
//! Port of `Src/patchlevel.h`. The C header defines a single
//! preprocessor constant `ZSH_PATCHLEVEL` that names the upstream
//! source revision the rest of the tree was built from. It's read
//! by `init.c` to populate the `$ZSH_PATCHLEVEL` shell parameter
//! and by the `zsh --version` startup-banner code.
//!
//! C source: 1 `#define`, 0 structs/enums/ported.

/// Port of `#define ZSH_PATCHLEVEL` from `Src/patchlevel.h:1`.
///
/// The upstream source-revision tag the C tree was generated from.
/// Format follows the convention `zsh-MAJOR.MINOR.PATCH-test-N-gHASH`
/// (where the trailing `-N-gHASH` is appended by `git describe`
/// during the upstream release process).
///
/// zshrs reads this constant verbatim from the upstream snapshot in
/// `src/zsh/Src/patchlevel.h` so the `$ZSH_PATCHLEVEL` shell
/// parameter (params.rs:1690) reports the same value zsh would on
/// the same source tree.
pub const ZSH_PATCHLEVEL: &str = "zsh-5.9-465-g6b9704e"; // c:1

/// Port of `#define ZSH_VERSION` (generated by `Src/Makemod:544`).
///
/// C body: `echo '#define ZSH_VERSION "'$(VERSION)'"' > $@`
/// — the build glue writes `VERSION` from `Config/version.mk` into
/// a generated header that init.c reads. zshrs holds the same value
/// as a Rust `const` since the build is cargo-driven, not make-driven.
/// Read by `params.rs::createparamtable` (c:966 — `setsparam("ZSH_VERSION", ZSH_VERSION)`)
/// and by the `--version` startup banner.
pub const ZSH_VERSION: &str = "5.9.0.3-test"; // Config/version.mk:VERSION

#[cfg(test)]
mod tests {
    use super::*;

    /// `$ZSH_PATCHLEVEL` is read at params.rs:1690 — pin both the
    /// snapshot value and its `zsh-MAJOR.MINOR-N-gHASH` shape. If
    /// upstream tags drop the `-g<hash>` suffix this fails — that's
    /// the git-describe contract zsh's version-reporting code relies
    /// on.
    #[test]
    fn patchlevel_value_and_git_describe_shape() {
        let _g = crate::test_util::global_state_lock();
        assert_eq!(ZSH_PATCHLEVEL, "zsh-5.9-465-g6b9704e");
        assert!(
            ZSH_PATCHLEVEL.contains("-g"),
            "git-describe `-g<hash>` suffix is load-bearing"
        );
    }

    /// `$ZSH_VERSION` is read at params.rs `createparamtable` (c:966)
    /// and by the `--version` startup banner (Src/init.c:436). Pin
    /// the upstream Config/version.mk VERSION value so version-aware
    /// scripts (e.g. `[[ $ZSH_VERSION = 5.9.* ]]`) keep working when
    /// the snapshot rolls forward.
    #[test]
    fn zsh_version_matches_upstream_config_version() {
        let _g = crate::test_util::global_state_lock();
        assert_eq!(ZSH_VERSION, "5.9.0.3-test");
        // Shape: MAJOR.MINOR[.PATCH[.SUB][-tag]]
        let major = ZSH_VERSION.split('.').next().unwrap_or("");
        assert!(
            major.chars().all(|c| c.is_ascii_digit()) && !major.is_empty(),
            "ZSH_VERSION must start with numeric MAJOR (got {ZSH_VERSION:?})"
        );
    }

    // ─── zsh-corpus pins for version constants ──────────────────────

    /// `ZSH_PATCHLEVEL` is non-empty.
    #[test]
    fn patchlevel_corpus_nonempty() {
        assert!(!ZSH_PATCHLEVEL.is_empty());
    }

    /// `ZSH_PATCHLEVEL` starts with "zsh-" prefix.
    #[test]
    fn patchlevel_corpus_zsh_prefix() {
        assert!(
            ZSH_PATCHLEVEL.starts_with("zsh-"),
            "patchlevel must start with `zsh-`, got {ZSH_PATCHLEVEL:?}"
        );
    }

    /// `ZSH_VERSION` follows MAJOR.MINOR format with at least one dot.
    #[test]
    fn patchlevel_corpus_version_has_dot() {
        assert!(
            ZSH_VERSION.contains('.'),
            "ZSH_VERSION must contain a dot (MAJOR.MINOR), got {ZSH_VERSION:?}"
        );
    }

    /// `ZSH_VERSION` MAJOR is "5" (current zsh series).
    #[test]
    fn patchlevel_corpus_version_major_is_five() {
        let major = ZSH_VERSION.split('.').next().unwrap();
        assert_eq!(major, "5", "current zsh is in the 5.x series");
    }

    /// `ZSH_VERSION` MINOR is parseable as integer.
    #[test]
    fn patchlevel_corpus_version_minor_parses() {
        let parts: Vec<&str> = ZSH_VERSION.split('.').collect();
        assert!(parts.len() >= 2, "must have MAJOR.MINOR");
        let minor: Result<i32, _> = parts[1].parse();
        assert!(minor.is_ok(), "MINOR must parse: {parts:?}");
    }

    /// Constants are distinct (patchlevel != version since patchlevel
    /// has the `-N-gHASH` tail).
    #[test]
    fn patchlevel_corpus_patchlevel_differs_from_version() {
        assert_ne!(ZSH_PATCHLEVEL, ZSH_VERSION);
    }

    // ═══════════════════════════════════════════════════════════════════
    // Additional C-parity tests for Src/patchlevel.h constants.
    // ═══════════════════════════════════════════════════════════════════

    /// ZSH_PATCHLEVEL has ≥ 4 dash-separated segments (zsh-VER-N-gHASH).
    #[test]
    fn patchlevel_has_four_dash_segments() {
        let parts: Vec<&str> = ZSH_PATCHLEVEL.split('-').collect();
        assert!(
            parts.len() >= 4,
            "patchlevel must have ≥ 4 dash segments, got {:?}",
            parts
        );
    }

    /// ZSH_PATCHLEVEL hash segment starts with 'g' (git-describe).
    #[test]
    fn patchlevel_hash_starts_with_g() {
        let last = ZSH_PATCHLEVEL.rsplit('-').next().unwrap_or("");
        assert!(
            last.starts_with('g'),
            "last segment {:?} must start with 'g'",
            last
        );
    }

    /// ZSH_PATCHLEVEL commit-count segment is numeric.
    #[test]
    fn patchlevel_commit_count_is_numeric() {
        let parts: Vec<&str> = ZSH_PATCHLEVEL.split('-').collect();
        if parts.len() >= 4 {
            let count_part = parts[2];
            let parsed: Result<i32, _> = count_part.parse();
            assert!(parsed.is_ok(), "commit-count {:?} must parse", count_part);
        }
    }

    /// ZSH_VERSION has no spaces.
    #[test]
    fn zsh_version_no_spaces() {
        assert!(!ZSH_VERSION.contains(' '));
    }

    /// ZSH_PATCHLEVEL has no spaces.
    #[test]
    fn zsh_patchlevel_no_spaces() {
        assert!(!ZSH_PATCHLEVEL.contains(' '));
    }

    /// Both constants are ASCII (parse-safe across all locales).
    #[test]
    fn version_strings_are_ascii() {
        assert!(ZSH_VERSION.is_ascii());
        assert!(ZSH_PATCHLEVEL.is_ascii());
    }

    /// Both have no trailing whitespace.
    #[test]
    fn version_strings_no_trailing_ws() {
        assert_eq!(ZSH_VERSION.trim_end(), ZSH_VERSION);
        assert_eq!(ZSH_PATCHLEVEL.trim_end(), ZSH_PATCHLEVEL);
    }

    /// MAJOR.MINOR from ZSH_VERSION appears inside ZSH_PATCHLEVEL.
    #[test]
    fn patchlevel_contains_major_minor_from_version() {
        let mm: String = ZSH_VERSION
            .split('.')
            .take(2)
            .collect::<Vec<_>>()
            .join(".");
        assert!(
            ZSH_PATCHLEVEL.contains(&mm),
            "patchlevel {:?} must contain {}",
            ZSH_PATCHLEVEL,
            mm
        );
    }

    // ═══════════════════════════════════════════════════════════════════
    // Additional C-parity tests for Src/patchlevel.h + Config/version.mk.
    // ═══════════════════════════════════════════════════════════════════

    /// ZSH_PATCHLEVEL hash after 'g' is a hex commit prefix.
    #[test]
    fn patchlevel_hash_after_g_is_hex() {
        let last = ZSH_PATCHLEVEL.rsplit('-').next().unwrap_or("");
        let hash = last.trim_start_matches('g');
        assert!(!hash.is_empty(), "hash must be non-empty after 'g'");
        assert!(
            hash.chars().all(|c| c.is_ascii_hexdigit()),
            "git-describe hash {:?} must be hex",
            hash
        );
    }

    /// ZSH_PATCHLEVEL hash prefix length is reasonable (≥7 for git short SHA).
    #[test]
    fn patchlevel_hash_short_sha_length() {
        let last = ZSH_PATCHLEVEL.rsplit('-').next().unwrap_or("");
        let hash = last.trim_start_matches('g');
        assert!(
            hash.len() >= 7 && hash.len() <= 40,
            "git short SHA must be 7-40 chars, got {} ({:?})",
            hash.len(),
            hash
        );
    }

    /// ZSH_PATCHLEVEL commit count is non-negative (no negative numbers).
    #[test]
    fn patchlevel_commit_count_non_negative() {
        let parts: Vec<&str> = ZSH_PATCHLEVEL.split('-').collect();
        if parts.len() >= 4 {
            let count: i32 = parts[2].parse().unwrap_or(-1);
            assert!(count >= 0, "commit count must be non-negative: {}", count);
        }
    }

    /// ZSH_VERSION components all parse as numeric (except possible `-tag` tail).
    #[test]
    fn zsh_version_components_numeric_until_tag() {
        let no_tag = ZSH_VERSION.split('-').next().unwrap_or("");
        for (i, comp) in no_tag.split('.').enumerate() {
            let parsed: Result<u32, _> = comp.parse();
            assert!(
                parsed.is_ok(),
                "ZSH_VERSION component[{}] = {:?} must parse as u32",
                i,
                comp
            );
        }
    }

    /// ZSH_VERSION MAJOR.MINOR is at least 5.9 (current upstream minimum).
    #[test]
    fn zsh_version_meets_minimum_5_9() {
        let no_tag = ZSH_VERSION.split('-').next().unwrap_or("");
        let parts: Vec<u32> = no_tag.split('.').filter_map(|s| s.parse().ok()).collect();
        assert!(parts.len() >= 2, "MAJOR.MINOR required");
        let major = parts[0];
        let minor = parts[1];
        assert!(
            major > 5 || (major == 5 && minor >= 9),
            "ZSH_VERSION must be ≥ 5.9, got {}.{}",
            major,
            minor
        );
    }

    /// ZSH_PATCHLEVEL has no NUL bytes (C-string safety).
    #[test]
    fn zsh_patchlevel_has_no_nul_bytes() {
        assert!(!ZSH_PATCHLEVEL.contains('\0'));
    }

    /// ZSH_VERSION has no NUL bytes (C-string safety).
    #[test]
    fn zsh_version_has_no_nul_bytes() {
        assert!(!ZSH_VERSION.contains('\0'));
    }

    /// ZSH_PATCHLEVEL doesn't start with whitespace.
    #[test]
    fn zsh_patchlevel_no_leading_whitespace() {
        assert!(!ZSH_PATCHLEVEL.starts_with(char::is_whitespace));
    }

    /// ZSH_VERSION doesn't start with whitespace.
    #[test]
    fn zsh_version_no_leading_whitespace() {
        assert!(!ZSH_VERSION.starts_with(char::is_whitespace));
    }

    /// Both constants are stable across reads (compile-time const).
    #[test]
    fn version_constants_are_stable() {
        for _ in 0..100 {
            assert_eq!(ZSH_PATCHLEVEL, "zsh-5.9-465-g6b9704e");
            assert_eq!(ZSH_VERSION, "5.9.0.3-test");
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    // Additional C-parity tests for Src/patchlevel.h + Config/version.mk
    // ═══════════════════════════════════════════════════════════════════

    /// Both constants are `&'static str` (compile-time pin).
    #[test]
    fn version_constants_static_str_type() {
        let _: &'static str = ZSH_PATCHLEVEL;
        let _: &'static str = ZSH_VERSION;
    }

    /// ZSH_PATCHLEVEL is reproducible byte-for-byte across address-of reads.
    #[test]
    fn zsh_patchlevel_address_is_stable() {
        let p1 = ZSH_PATCHLEVEL.as_ptr();
        let p2 = ZSH_PATCHLEVEL.as_ptr();
        assert_eq!(p1, p2, "PATCHLEVEL must have stable static address");
    }

    /// ZSH_VERSION reproducible byte-for-byte across address-of reads.
    #[test]
    fn zsh_version_address_is_stable() {
        let p1 = ZSH_VERSION.as_ptr();
        let p2 = ZSH_VERSION.as_ptr();
        assert_eq!(p1, p2, "VERSION must have stable static address");
    }

    /// ZSH_PATCHLEVEL length is reasonable (10..200 bytes — not empty,
    /// not absurdly long).
    #[test]
    fn zsh_patchlevel_length_in_sane_range() {
        let n = ZSH_PATCHLEVEL.len();
        assert!(n >= 10 && n <= 200,
            "PATCHLEVEL length {} must be in [10, 200]", n);
    }

    /// ZSH_VERSION length is reasonable (3..30 bytes).
    #[test]
    fn zsh_version_length_in_sane_range() {
        let n = ZSH_VERSION.len();
        assert!(n >= 3 && n <= 30,
            "VERSION length {} must be in [3, 30]", n);
    }

    /// ZSH_PATCHLEVEL doesn't contain any uppercase hex above 9
    /// (git-describe uses lowercase hex per `--abbrev` convention).
    #[test]
    fn zsh_patchlevel_hash_is_lowercase_hex() {
        let last = ZSH_PATCHLEVEL.rsplit('-').next().unwrap_or("");
        let hash = last.trim_start_matches('g');
        for c in hash.chars() {
            assert!(
                !c.is_ascii_uppercase(),
                "git-describe hash uses lowercase hex; found uppercase {:?}", c);
        }
    }

    /// ZSH_PATCHLEVEL split on '-' all segments non-empty (no `--`).
    #[test]
    fn zsh_patchlevel_no_empty_segments() {
        for seg in ZSH_PATCHLEVEL.split('-') {
            assert!(!seg.is_empty(),
                "PATCHLEVEL must have no empty segments (no consecutive dashes)");
        }
    }

    /// ZSH_VERSION split on '.' first 2 segments non-empty.
    #[test]
    fn zsh_version_major_minor_segments_non_empty() {
        let parts: Vec<&str> = ZSH_VERSION.split('.').collect();
        assert!(parts.len() >= 2);
        assert!(!parts[0].is_empty(), "MAJOR non-empty");
        assert!(!parts[1].is_empty(), "MINOR non-empty");
    }

    /// ZSH_PATCHLEVEL doesn't contain trailing newline.
    #[test]
    fn zsh_patchlevel_no_trailing_newline() {
        assert!(!ZSH_PATCHLEVEL.ends_with('\n'));
        assert!(!ZSH_PATCHLEVEL.ends_with('\r'));
    }

    /// ZSH_VERSION doesn't contain trailing newline.
    #[test]
    fn zsh_version_no_trailing_newline() {
        assert!(!ZSH_VERSION.ends_with('\n'));
        assert!(!ZSH_VERSION.ends_with('\r'));
    }

    /// Both constants are valid UTF-8 (trivially true for &str but
    /// pin the contract).
    #[test]
    fn version_constants_valid_utf8() {
        let _ = std::str::from_utf8(ZSH_PATCHLEVEL.as_bytes()).expect("PATCHLEVEL valid UTF-8");
        let _ = std::str::from_utf8(ZSH_VERSION.as_bytes()).expect("VERSION valid UTF-8");
    }
}
