//! Port of `_regex_arguments` from `Completion/Base/Utility/_regex_arguments`.
//!
//! Full upstream body (86 lines verbatim):
//! ```text
//! sh: 1  #autoload
//! sh: 2
//! sh: 3  ## usage: _regex_arguments funcname regex
//! sh: 4
//! sh: 5  # _regex_arguments compiles `regex' and emits the result of the state
//! sh: 6  # machine into the function `funcname'. `funcname' parses a command line
//! sh: 7  # according to `regex' and evaluates appropriate actions in `regex'. Before
//! sh: 8  # parsing the command line string is generated by concatenating `words'
//! sh: 9  # (before `PREFIX') and `PREFIX' with a separator NUL ($'\0').
//! sh:10
//! sh:11  # The `regex' is defined as follows.
//! sh:12
//! sh:13  ## regex word definition:
//! sh:14
//! sh:15  # pattern = "/" ( glob | "[]" ) "/" [ "+" | "-" ]
//! sh:16  # lookahead = "%" glob "%"
//! sh:17  # guard = "-" zsh-code-to-eval
//! sh:18  # caction = ":" tag ":" descr ":" zsh-code-to-eval
//! sh:19  # action = "{" zsh-code-to-eval "}"
//! sh:20
//! sh:21  ## regex word sequence definition:
//! sh:22
//! sh:23  # element = pattern [ lookahead ] [ guard ] [ caction ]
//! sh:24  #
//! sh:25  # regex = element
//! sh:26  #	| "(" regex ")"
//! sh:27  #	| regex "#"
//! sh:28  #	| ( regex | action ) #
//! sh:29  #	| regex "|" regex
//! sh:30
//! sh:31  # example:
//! sh:32
//! sh:33  # compdef _tst tst
//! sh:34
//! sh:35  # _regex_arguments _tst /$'[^\0]#\0'/ /$'[^\0]#\0'/ :'compadd aaa'
//! sh:36  #  _tst complete `aaa' for first argument.
//! sh:37  #  First $'[^\0]#\0' is required to match with command name.
//! sh:38
//! sh:39  # _regex_arguments _tst /$'[^\0]#\0'/ \( /$'[^\0]#\0'/ :'compadd aaa' /$'[^\0]#\0'/ :'compadd bbb' \) \#
//! sh:40  #  _tst complete `aaa' for (2i+1)th argument and `bbb' for (2i)th argument.
//! sh:41
//! sh:42  # _regex_arguments _tst /$'[^\0]#\0'/ \( /$'[^\0]#\0'/ :'compadd aaa' \| /$'[^\0]#\0'/ :'compadd bbb' \) \#
//! sh:43  #  _tst complete `aaa' or `bbb'.
//! sh:44
//! sh:45  ## Recursive decent regex parser
//! sh:46
//! sh:47  # return status of parser functions:
//! sh:48
//! sh:49  # 0 : success
//! sh:50  # 1 : parse error
//! sh:51  # 2 : fatal parse error
//! sh:52
//! sh:53  _ra_comp () {
//! sh:54    _ra_actions=("$_ra_actions[@]" "$1")
//! sh:55  }
//! sh:56
//! sh:57  _regex_arguments () {
//! sh:58    local regex funcname="$1"
//! sh:59    shift
//! sh:60    regex=(${@:/(#b):(*)/":_ra_comp ${(qqqq)match[1]}"})
//! sh:61
//! sh:62    eval \
//! sh:63    "$funcname"' () {
//! sh:64      local _ra_p1 _ra_p2 _ra_left _ra_right _ra_com expl tmp nm="$compstate[nmatches]"
//! sh:65      local _ra_actions _ra_line="${(pj:\0:)${(@)words[1,CURRENT - 1]:Q}}"$'\''\0'\''"$PREFIX"
//! sh:66      _ra_actions=()
//! sh:67      zregexparse -c _ra_p1 _ra_p2 "$_ra_line" '"${(j: :)${(qqqq)regex[@]}}"'
//! sh:68      case "$?" in
//! sh:69      0|2) _message "no more arguments";;
//! sh:70      1)
//! sh:71        if [[ "$_ra_line[_ra_p1 + 1, -1]" = *$'\''\0'\''* ]]; then
//! sh:72  	_message "parse failed before current word"
//! sh:73        else
//! sh:74  	_ra_left="$_ra_line[_ra_p1 + 1, _ra_p2]"
//! sh:75  	_ra_right="$_ra_line[_ra_p2 + 1, -1]"
//! sh:76  	compset -p $(( $#PREFIX - $#_ra_line + $_ra_p1 ))
//! sh:77  	(( $#_ra_actions )) && _alternative "$_ra_actions[@]"
//! sh:78        fi
//! sh:79        ;;
//! sh:80      3) _message "invalid regex";;
//! sh:81      esac
//! sh:82      [[ nm -ne "$compstate[nmatches]" ]]
//! sh:83    }'
//! sh:84  }
//! sh:85
//! sh:86  _regex_arguments "$@"
//! ```
//!
//! Upstream compiles the patterns into a generated shell fn.
//!
//! Strict Rust port: walks the patterns at completion-time (skipping
//! the compile step), first matching pattern wins. Emits the
//! description as the group explanation AND dispatches the action
//! via `_call_function` so registered Rust callbacks (or shell-fn
//! shims) actually fire when a pattern hits.



use crate::compsys::base::MainCompleteState;
use crate::compsys::ported::_call_function::_call_function;

/// _regex_arguments - Complete using regex-based argument specs.
///
/// `name` is forwarded as the generated-fn name (matches upstream's
/// `$1`); not used for dispatch at this layer but kept in the
/// signature for parity with the shell call site. `patterns` is a
/// slice of `(regex, description, action_fn_name)` triples.
pub fn _regex_arguments(
    state: &mut MainCompleteState,
    _name: &str,
    patterns: &[(String, String, String)],
) -> bool {
    let current = state.comp.params.current_word();

    for (pattern, desc, action) in patterns {
        let Ok(re) = regex_lite::Regex::new(pattern) else {
            continue;
        };
        if !re.is_match(&current) {
            continue;
        }
        state.comp.begin_group("regex", true);
        state.comp.add_explanation(desc.clone(), Some("regex"));
        state.comp.end_group();
        // Dispatch the registered action. The shell version `eval`s
        // the action string; we resolve `action` as a fn name and
        // dispatch through `_call_function`. Empty action = no-op.
        if !action.is_empty() {
            let _ = _call_function(state, action);
        }
        return true;
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn first_matching_pattern_wins() {
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "abc123".into();
        let patterns = vec![
            ("^xyz".into(), "no match".into(), "".into()),
            ("^abc".into(), "matches abc-prefix".into(), "".into()),
            ("^.*".into(), "matches anything".into(), "".into()),
        ];
        assert!(_regex_arguments(&mut state, "x", &patterns));
        let exps: Vec<String> = state
            .comp
            .groups
            .iter()
            .flat_map(|g| g.explanations.iter().cloned())
            .collect();
        assert!(
            exps.contains(&"matches abc-prefix".to_string()),
            "got {exps:?}"
        );
    }

    #[test]
    fn no_pattern_matches_returns_false() {
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "abc".into();
        let patterns = vec![("^xyz".into(), "no".into(), "".into())];
        assert!(!_regex_arguments(&mut state, "x", &patterns));
    }

    #[test]
    fn invalid_regex_pattern_skipped() {
        let mut state = MainCompleteState::new("", 0);
        let patterns = vec![
            ("[bad-regex".into(), "bad".into(), "".into()),
            (".*".into(), "good".into(), "".into()),
        ];
        assert!(_regex_arguments(&mut state, "x", &patterns));
    }

    #[test]
    fn empty_patterns_returns_false() {
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "anything".into();
        assert!(!_regex_arguments(&mut state, "x", &[]));
    }

    #[test]
    fn anchored_end_regex_works() {
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "abc.txt".into();
        let patterns = vec![
            ("\\.txt$".into(), "text file".into(), "".into()),
            (".*".into(), "fallback".into(), "".into()),
        ];
        assert!(_regex_arguments(&mut state, "x", &patterns));
        let exps: Vec<String> = state
            .comp
            .groups
            .iter()
            .flat_map(|g| g.explanations.iter().cloned())
            .collect();
        assert!(exps.contains(&"text file".to_string()), "got {exps:?}");
    }

    #[test]
    fn group_name_is_regex_for_matched_dispatch() {
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "x".into();
        let patterns = vec![(".".into(), "explanation".into(), "act".into())];
        assert!(_regex_arguments(&mut state, "fnname", &patterns));
        assert!(state.comp.groups.iter().any(|g| g.name == "regex"));
    }

    #[test]
    fn current_word_not_prefix_drives_matching() {
        let mut state = MainCompleteState::new("", 0);
        // Empty words → current_word() is empty.
        let patterns = vec![
            ("^x$".into(), "x-only".into(), "".into()),
            ("^$".into(), "empty".into(), "".into()),
        ];
        assert!(_regex_arguments(&mut state, "x", &patterns));
        let exps: Vec<String> = state
            .comp
            .groups
            .iter()
            .flat_map(|g| g.explanations.iter().cloned())
            .collect();
        assert!(
            exps.contains(&"empty".to_string()),
            "empty current_word should match `^$`; got {exps:?}"
        );
    }

    #[test]
    fn registered_action_fires_for_matching_pattern() {
        use crate::compsys::ported::_call_function::{register, unregister};
        use std::sync::atomic::{AtomicUsize, Ordering};
        static FIRED: AtomicUsize = AtomicUsize::new(0);
        FIRED.store(0, Ordering::SeqCst);
        register(
            "_rxargs_action",
            Box::new(|_| {
                FIRED.fetch_add(1, Ordering::SeqCst);
                true
            }),
        );
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "go".into();
        let patterns = vec![("^go".into(), "go-prefix".into(), "_rxargs_action".into())];
        assert!(_regex_arguments(&mut state, "x", &patterns));
        unregister("_rxargs_action");
        assert_eq!(
            FIRED.load(Ordering::SeqCst),
            1,
            "registered action must fire exactly once on match"
        );
    }

    #[test]
    fn action_does_not_fire_when_no_pattern_matches() {
        use crate::compsys::ported::_call_function::{register, unregister};
        use std::sync::atomic::{AtomicUsize, Ordering};
        static FIRED: AtomicUsize = AtomicUsize::new(0);
        FIRED.store(0, Ordering::SeqCst);
        register(
            "_rxargs_skip",
            Box::new(|_| {
                FIRED.fetch_add(1, Ordering::SeqCst);
                true
            }),
        );
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "abc".into();
        let patterns = vec![("^XX$".into(), "no".into(), "_rxargs_skip".into())];
        assert!(!_regex_arguments(&mut state, "x", &patterns));
        unregister("_rxargs_skip");
        assert_eq!(FIRED.load(Ordering::SeqCst), 0);
    }

    #[test]
    fn unregistered_action_name_does_not_panic() {
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "x".into();
        let patterns = vec![(".".into(), "desc".into(), "not-registered".into())];
        // Should NOT panic — `_call_function` returns false for
        // unknown names.
        assert!(_regex_arguments(&mut state, "x", &patterns));
    }

    #[test]
    fn second_matching_action_does_not_fire() {
        // First-match-wins — the second pattern's action MUST NOT
        // fire even though its regex would also match.
        use crate::compsys::ported::_call_function::{register, unregister};
        use std::sync::atomic::{AtomicBool, Ordering};
        static FIRED: AtomicBool = AtomicBool::new(false);
        FIRED.store(false, Ordering::SeqCst);
        register(
            "_rxargs_second",
            Box::new(|_| {
                FIRED.store(true, Ordering::SeqCst);
                true
            }),
        );
        let mut state = MainCompleteState::new("", 0);
        state.comp.params.prefix = "abc".into();
        let patterns = vec![
            ("^abc".into(), "first".into(), "".into()),
            (".*".into(), "second".into(), "_rxargs_second".into()),
        ];
        assert!(_regex_arguments(&mut state, "x", &patterns));
        unregister("_rxargs_second");
        assert!(!FIRED.load(Ordering::SeqCst));
    }
}
