//! Port of `_regex_arguments` from `Completion/Base/Utility/_regex_arguments`.
//!
//! Full upstream body (86 lines verbatim):
//! ```text
//! sh: 1  #autoload
//! sh: 2
//! sh: 3  ## usage: _regex_arguments funcname regex
//! sh: 4
//! sh: 5  # _regex_arguments compiles `regex' and emits the result of the state
//! sh: 6  # machine into the function `funcname'. `funcname' parses a command line
//! sh: 7  # according to `regex' and evaluates appropriate actions in `regex'. Before
//! sh: 8  # parsing the command line string is generated by concatenating `words'
//! sh: 9  # (before `PREFIX') and `PREFIX' with a separator NUL ($'\0').
//! sh:10
//! sh:11  # The `regex' is defined as follows.
//! sh:12
//! sh:13  ## regex word definition:
//! sh:14
//! sh:15  # pattern = "/" ( glob | "[]" ) "/" [ "+" | "-" ]
//! sh:16  # lookahead = "%" glob "%"
//! sh:17  # guard = "-" zsh-code-to-eval
//! sh:18  # caction = ":" tag ":" descr ":" zsh-code-to-eval
//! sh:19  # action = "{" zsh-code-to-eval "}"
//! sh:20
//! sh:21  ## regex word sequence definition:
//! sh:22
//! sh:23  # element = pattern [ lookahead ] [ guard ] [ caction ]
//! sh:24  #
//! sh:25  # regex = element
//! sh:26  #	| "(" regex ")"
//! sh:27  #	| regex "#"
//! sh:28  #	| ( regex | action ) #
//! sh:29  #	| regex "|" regex
//! sh:30
//! sh:31  # example:
//! sh:32
//! sh:33  # compdef _tst tst
//! sh:34
//! sh:35  # _regex_arguments _tst /$'[^\0]#\0'/ /$'[^\0]#\0'/ :'compadd aaa'
//! sh:36  #  _tst complete `aaa' for first argument.
//! sh:37  #  First $'[^\0]#\0' is required to match with command name.
//! sh:38
//! sh:39  # _regex_arguments _tst /$'[^\0]#\0'/ \( /$'[^\0]#\0'/ :'compadd aaa' /$'[^\0]#\0'/ :'compadd bbb' \) \#
//! sh:40  #  _tst complete `aaa' for (2i+1)th argument and `bbb' for (2i)th argument.
//! sh:41
//! sh:42  # _regex_arguments _tst /$'[^\0]#\0'/ \( /$'[^\0]#\0'/ :'compadd aaa' \| /$'[^\0]#\0'/ :'compadd bbb' \) \#
//! sh:43  #  _tst complete `aaa' or `bbb'.
//! sh:44
//! sh:45  ## Recursive decent regex parser
//! sh:46
//! sh:47  # return status of parser functions:
//! sh:48
//! sh:49  # 0 : success
//! sh:50  # 1 : parse error
//! sh:51  # 2 : fatal parse error
//! sh:52
//! sh:53  _ra_comp () {
//! sh:54    _ra_actions=("$_ra_actions[@]" "$1")
//! sh:55  }
//! sh:56
//! sh:57  _regex_arguments () {
//! sh:58    local regex funcname="$1"
//! sh:59    shift
//! sh:60    regex=(${@:/(#b):(*)/":_ra_comp ${(qqqq)match[1]}"})
//! sh:61
//! sh:62    eval \
//! sh:63    "$funcname"' () {
//! sh:64      local _ra_p1 _ra_p2 _ra_left _ra_right _ra_com expl tmp nm="$compstate[nmatches]"
//! sh:65      local _ra_actions _ra_line="${(pj:\0:)${(@)words[1,CURRENT - 1]:Q}}"$'\''\0'\''"$PREFIX"
//! sh:66      _ra_actions=()
//! sh:67      zregexparse -c _ra_p1 _ra_p2 "$_ra_line" '"${(j: :)${(qqqq)regex[@]}}"'
//! sh:68      case "$?" in
//! sh:69      0|2) _message "no more arguments";;
//! sh:70      1)
//! sh:71        if [[ "$_ra_line[_ra_p1 + 1, -1]" = *$'\''\0'\''* ]]; then
//! sh:72  	_message "parse failed before current word"
//! sh:73        else
//! sh:74  	_ra_left="$_ra_line[_ra_p1 + 1, _ra_p2]"
//! sh:75  	_ra_right="$_ra_line[_ra_p2 + 1, -1]"
//! sh:76  	compset -p $(( $#PREFIX - $#_ra_line + $_ra_p1 ))
//! sh:77  	(( $#_ra_actions )) && _alternative "$_ra_actions[@]"
//! sh:78        fi
//! sh:79        ;;
//! sh:80      3) _message "invalid regex";;
//! sh:81      esac
//! sh:82      [[ nm -ne "$compstate[nmatches]" ]]
//! sh:83    }'
//! sh:84  }
//! sh:85
//! sh:86  _regex_arguments "$@"
//! ```
//!
//! Upstream compiles the patterns into a generated shell fn.
//!
//! Strict Rust port: walks the patterns at completion-time (skipping
//! the compile step), first matching pattern wins. Emits the
//! description as the group explanation AND dispatches the action
//! via `_call_function` so registered Rust callbacks (or shell-fn
//! shims) actually fire when a pattern hits.

// GUTTED 2026-05-24 — body removed.
// Previously depended on `crate::compsys::compcore::CompletionState`
// and friends, which were deleted as duplicates of the real shell-side
// state in `src/ported/zle/compcore.rs`. Engine port body must be
// re-implemented to call into `crate::ported::zle::compcore::addmatch`
// against shell-side globals (PREFIX/SUFFIX/matches/etc.).
