//! Port of `_oldlist` from `Completion/Base/Completer/_oldlist`.
//!
//! Full upstream body (57 lines verbatim):
//! ```text
//! sh: 1  #autoload
//! sh: 2
//! sh: 3  [[ _matcher_num -gt 1 || $_lastcomp[nmatches] -eq 0 ]] && return 1
//! sh: 4
//! sh: 5  local list
//! sh: 6
//! sh: 7  zstyle -s ":completion:${curcontext}:" old-list list
//! sh: 8
//! sh: 9  # If this is a listing widget and there is already an old list,
//! sh:10  # and either the style :oldlist:old-list is `always', or it is not `never'
//! sh:11  # and the list is not already shown, then use the existing list for listing
//! sh:12  # (even if it was generated by another widget).
//! sh:13  # Do this also if there is an old list and it was generated by the
//! sh:14  # completer named by the oldlist_list key.
//! sh:15
//! sh:16  if [[ -n $compstate[old_list] && $list != never &&
//! sh:17        $LASTWIDGET != _complete_help && $WIDGET != _complete_help ]]; then
//! sh:18    if [[ $WIDGETSTYLE = *list* && ( $list = always || $list != shown ) ]]; then
//! sh:19      compstate[old_list]=keep
//! sh:20      return 0
//! sh:21    elif [[ $list = *${_lastcomp[completer]}* ]]; then
//! sh:22      [[ "$_lastcomp[insert]" = unambig* ]] && compstate[to_end]=single
//! sh:23      compstate[old_list]=keep
//! sh:24      if [[ -o automenu ]]; then
//! sh:25        compstate[insert]=menu
//! sh:26      else
//! sh:27        compadd -Qs "$SUFFIX" - "$PREFIX"
//! sh:28      fi
//! sh:29      return 0
//! sh:30    fi
//! sh:31  fi
//! sh:32
//! sh:33  # If this is a completion widget, and we have a completion inserted already,
//! sh:34  # and the style :oldlist:old-menu is `true', then we cycle through the
//! sh:35  # existing list (even if it was generated by another widget).
//! sh:36
//! sh:37  if [[ -z $compstate[old_insert] && -n $compstate[old_list] &&
//! sh:38        ( $_lastcomp[nmatches] -ne 0 || $WIDGET != $LASTWIDGET ) &&
//! sh:39        $LASTWIDGET != _complete_help && $WIDGET != _complete_help ]]; then
//! sh:40    compstate[old_list]=keep
//! sh:41    return 0
//! sh:42  elif [[ $WIDGETSTYLE = *complete(|-prefix|-word) ]] &&
//! sh:43       zstyle -T ":completion:${curcontext}:" old-menu; then
//! sh:44    if [[ -n $compstate[old_insert] ]]; then
//! sh:45      compstate[old_list]=keep
//! sh:46      if [[ $WIDGETSTYLE = *reverse* ]]; then
//! sh:47        compstate[insert]=$(( compstate[old_insert] - 1 ))
//! sh:48      else
//! sh:49        compstate[insert]=$(( compstate[old_insert] + 1 ))
//! sh:50      fi
//! sh:51    else
//! sh:52      return 1
//! sh:53    fi
//! sh:54    return 0
//! sh:55  fi
//! sh:56
//! sh:57  return 1
//! ```
//!
//! Strict Rust port: full upstream gate. Caller supplies ZLE widget
//! context (`widget`, `last_widget`, `widget_style`) which compsys
//! can't reach into directly, plus the resolved `old-list` /
//! `old-menu` style values. Returns `true` (shell `return 0` →
//! reuse old list) when ANY of the upstream branches accept;
//! mutates `compstate.old_list` / `to_end` / `insert` to match.

// GUTTED 2026-05-24 — body removed.
// Previously depended on `crate::compsys::compcore::CompletionState`
// and friends, which were deleted as duplicates of the real shell-side
// state in `src/ported/zle/compcore.rs`. Engine port body must be
// re-implemented to call into `crate::ported::zle::compcore::addmatch`
// against shell-side globals (PREFIX/SUFFIX/matches/etc.).
