#!/usr/bin/env python3
"""Ask ONE question about the REFERENCE shell: does it survive this completion?

    tests/compsys_fixtures/zsh_reference_probe.py --word 'BATCH ' \
        --control 'batch ' --trials 3 --json /tmp/probe.json

Every other harness in this repo compares two shells. This one deliberately
does not, and `zshrs` appears nowhere in it: the fixture it serves
(`reference_crash_uppercase_autoload.json`) records a defect in `zsh` itself,
and a claim about the reference shell must not depend on a second shell being
present to make it. A round-2 sweep scored seven of these cells `TIMEOUT`,
i.e. "nothing was proven"; they were the reference shell dying.

It boots `zsh -f -i`, sources the init `comptab_parity.py` builds (the full
user `fpath` plus `compinit -C -d <the zpwr dump>`), types WORD, presses TAB
and reports how the child ended:

    SIG11 / SIG10   killed by SIGSEGV / SIGBUS — the shell crashed
    exitN           exited on its own
    alive           still running when the budget ran out; killed by the probe

`--control` runs the same measurement on a word that must NOT crash, so a
"crashes" result is never just "this machine kills shells today".

Measurement note, learned the hard way in this file: EOF on the pty means the
child is gone, but it is not necessarily REAPED yet, so a bare
`waitpid(WNOHANG)` right after the read loop returns 0 and the run gets
labelled `alive`. That mislabelled 2 of 4 crashing trials here before it was
fixed, in the same direction as the original `TIMEOUT` mistake — a dead shell
read as a slow one. `wait_status()` now waits up to 2s for a status.
"""

import argparse
import glob
import json
import os
import pty
import select
import shlex
import subprocess
import sys
import tempfile
import time

SENTINEL = "@CT@"
ZSH = "zsh"


def dump_path():
    """The compinit dump comptab_parity.py would pick, or None."""
    for pat in ("~/.zpwr/local/.zcompdump*", "~/.zcompdump*"):
        hits = sorted(glob.glob(os.path.expanduser(pat)))
        if hits:
            return hits[0]
    return None


def user_fpath(zsh):
    """The fpath `zsh -f` sees on this host — the set the dump was built from."""
    out = subprocess.run([zsh, "-f", "-c", "print -rl -- $fpath"],
                         capture_output=True, text=True, timeout=20).stdout
    return [d for d in out.splitlines() if d and os.path.isdir(d)]


def build_init(dump, fpath_dirs):
    """comptab_parity.build_init's init, reproduced here rather than imported.

    Imported code would drift under us: three sibling harnesses are edited
    constantly and this file must keep answering the same question. The four
    lines that matter are the fpath, the dump, `compinit -C` and the prompt.
    """
    d = tempfile.mkdtemp(prefix="zsh_reference_probe_")
    path = os.path.join(d, "init.zsh")
    with open(path, "w") as f:
        f.write("# generated by tests/compsys_fixtures/zsh_reference_probe.py\n")
        f.write("PROMPT='%s '\nRPROMPT=''\nPS2='> '\nsetopt no_beep\n" % SENTINEL)
        if fpath_dirs:
            f.write("fpath=( %s )\n" % " ".join(shlex.quote(p) for p in fpath_dirs))
        if dump:
            f.write("autoload -Uz compinit\ncompinit -C -d %s\n" % shlex.quote(dump))
        else:
            f.write("autoload -Uz compinit\ncompinit -u\n")
        f.write("print -u2 ''\n")
    return path


def wait_status(pid, grace=2.0):
    """(verdict, reaped) — never call a dead-but-unreaped child `alive`."""
    deadline = time.time() + grace
    dead, status = os.waitpid(pid, os.WNOHANG)
    while dead == 0 and time.time() < deadline:
        time.sleep(0.05)
        dead, status = os.waitpid(pid, os.WNOHANG)
    if dead == 0:
        return "alive", False
    if os.WIFSIGNALED(status):
        return "SIG%d" % os.WTERMSIG(status), True
    return "exit%d" % os.WEXITSTATUS(status), True


def one_trial(word, init, zsh, budget, settle):
    """Type `word`, press TAB, and report how the shell ended."""
    pid, fd = pty.fork()
    if pid == 0:                                    # child: the shell under test
        env = {"TERM": "xterm-256color", "LANG": "C", "LC_ALL": "C",
               "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
               "HOME": os.environ.get("HOME", "/tmp"),
               "COLUMNS": "110", "LINES": "40"}
        os.execve(zsh, [os.path.basename(zsh), "-f", "-i"], env)
    buf = b""
    t0 = time.time()
    t_tab = None
    sourced = typed = tabbed = False
    eof = False
    while time.time() - t0 < budget:
        ready, _, _ = select.select([fd], [], [], 0.4)
        if ready:
            try:
                chunk = os.read(fd, 65536)
            except OSError:                          # pty closed under us
                chunk = b""
            if not chunk:
                eof = True
                break
            buf += chunk
        if not sourced and time.time() - t0 > 1.5:
            os.write(fd, ("source %s\n" % init).encode())
            sourced = True
            continue
        if sourced and not typed and SENTINEL.encode() in buf:
            time.sleep(0.5)
            os.write(fd, word.encode())
            typed = True
            continue
        if typed and not tabbed:
            time.sleep(0.5)
            os.write(fd, b"\t")
            tabbed = True
            t_tab = time.time()
            continue
        if tabbed and not ready and time.time() - t_tab > settle:
            break                                    # settled, shell still alive
    verdict, _ = wait_status(pid)
    if verdict == "alive":
        os.kill(pid, 9)
        os.waitpid(pid, 0)
    os.close(fd)
    return {"verdict": verdict, "seconds": round(time.time() - t0, 2),
            "eof": eof, "tail": repr(buf[-160:])}


def measure(word, init, args):
    trials = [one_trial(word, init, args.zsh, args.budget, args.settle)
              for _ in range(args.trials)]
    crashed = sum(1 for t in trials if t["verdict"].startswith("SIG"))
    return {"word": word, "trials": trials, "crashed": crashed,
            "n": len(trials),
            "signals": sorted({t["verdict"] for t in trials
                               if t["verdict"].startswith("SIG")})}


def main():
    ap = argparse.ArgumentParser(
        description="does the REFERENCE shell survive `<word><TAB>`?")
    ap.add_argument("--word", required=True,
                    help="what to type before TAB (include the trailing space)")
    ap.add_argument("--control", default=None,
                    help="a word that must NOT crash, measured the same way")
    ap.add_argument("--trials", type=int, default=3)
    ap.add_argument("--zsh", default=ZSH)
    ap.add_argument("--dump", default=None, help="compinit dump (default: the "
                                                 "zpwr dump this host has)")
    ap.add_argument("--budget", type=float, default=60.0,
                    help="seconds per trial before the shell is called alive")
    ap.add_argument("--settle", type=float, default=8.0,
                    help="quiet seconds after TAB that end a surviving trial")
    ap.add_argument("--json", default=None)
    args = ap.parse_args()

    import shutil
    zsh_abs = shutil.which(args.zsh)
    if not zsh_abs:
        sys.exit("zsh_reference_probe: %s not found on PATH" % args.zsh)
    args.zsh = os.path.abspath(zsh_abs)
    dump = args.dump or dump_path()
    init = build_init(dump, user_fpath(args.zsh))

    ver = subprocess.run([args.zsh, "--version"], capture_output=True,
                         text=True).stdout.strip()
    print("# zsh  : %s (%s)" % (ver, args.zsh))
    print("# dump : %s" % dump)
    print("# init : %s" % init)
    sys.stdout.flush()

    subject = measure(args.word, init, args)
    control = measure(args.control, init, args) if args.control else None
    for block, label in ((subject, "word"), (control, "control")):
        if block is None:
            continue
        for i, t in enumerate(block["trials"]):
            print("%-8s %-22r trial%d  %-8s %6.2fs"
                  % (label, block["word"], i, t["verdict"], t["seconds"]))
        print("%-8s %-22r %d/%d crashed%s"
              % (label, block["word"], block["crashed"], block["n"],
                 "  (%s)" % ",".join(block["signals"]) if block["signals"] else ""))
    sys.stdout.flush()

    doc = {"schema": "zsh-reference-probe/1", "zsh": ver, "zsh_path": args.zsh,
           "dump": dump, "init": init, "argv": sys.argv[1:],
           "subject": subject, "control": control}
    if args.json:
        with open(args.json, "w") as f:
            json.dump(doc, f, indent=1)
        print("# json: %s" % args.json)

    # Exit 0 means the recorded reference defect REPRODUCED: the word crashed at
    # least once and the control never did. Anything else is a change worth
    # looking at, which is the same convention the fixture runner uses.
    if not subject["crashed"]:
        return 1
    if control is not None and control["crashed"]:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
