echo ${var}
echo ${var:-default}
echo ${var:=assign}
echo ${var:?error}
echo ${var:+alt}
echo ${var#prefix}
echo ${var##longprefix}
echo ${var%suffix}
echo ${var%%longsuffix}
echo ${var/pat/rep}
echo ${var//pat/rep}
echo ${var:offset:length}
echo ${#var}
echo ${(U)var}
echo ${(L)var}
echo ${(P)var}
echo ${(qqq)var}
echo ${(j:,:)array}
echo ${(s:,:)str}
