[[ -f /tmp/x ]]
[[ -d /tmp ]]
[[ -e /tmp/x && -r /tmp/x ]]
[[ a == b || c != d ]]
[[ "$str" =~ ^[a-z]+$ ]]
[[ ! -f /tmp/x ]]
[[ -z $empty || -n $full ]]
[[ a < b ]]
[[ 5 -lt 10 ]]
[[ /tmp/a -nt /tmp/b ]]
