(( x = 1 + 2 * 3 ))
(( y = (a + b) / 2 ))
(( z = a < b ? a : b ))
(( count++ ))
(( ++count ))
(( count-- ))
(( total += value ))
(( bits = a & b | c ^ d ))
(( shifts = a << 2 | b >> 1 ))
(( arr[i] = arr[i-1] * 2 ))
echo $((1 + 1))
echo $(( 2 ** 10 ))
((flag = !0 && cond))
