# GENERATED by scripts/gen_parity_combos.py — do not hand-edit.
# Source fixture: scripts/parity_zstyle.zsh
# full config minus every `matcher-list`/`matcher` statement (2 dropped)
zstyle ':completion:*' auto-description 'Specify: %d'
zstyle ':completion:*' cache-path ${HOME}/.zpwr/local/zcompcache
zstyle ':completion:*' cache-policy zpwrMonthlyCachingPolicy
zstyle ':completion:*' complete-options on
zstyle ':completion:*' completer _expand _ignored _megacomplete _approximate _correct _fasd_zsh_word_complete_trigger
zstyle ':completion:*' delimiters @ / , %
zstyle ':completion:*' extra-verbose on
zstyle ':completion:*' format $'\C-[[1;31m-<<\C-[[0;34m%d\C-[[1;31m>>-\C-[[0m'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' group-order zpwr-regen zpwr-clean zpwr-travis zpwr-learn zpwr-search zpwr-env zpwr-update zpwr-cd zpwr-clipboard zpwr-emacs zpwr-vim zpwr-github zpwr-gitrepos zpwr-git zpwr-misc zpwr-send zpwr-forgit zpwr-log zpwr-diag zpwr-monitor c options commands aliases alias global-aliases suffix-aliases functions builtins reserved-words parameters argument-rest strings identifiers hosts commits heads commit-tags heads-local heads-remote recent-branches tags commit-objects remote-branch-names-noprefix corrections packages npm-search npm-cache remote-crate remote-gem remote-pip original globbed-files files fasd-file fasd zdir local-directories tmux contexts last-ten last-clip
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' insert-sections on
zstyle ':completion:*' list-colors 'ma=37;1;4;44'
zstyle ':completion:*' list-grouped false
zstyle ':completion:*' list-prompt $'\C-[[1;31m-<<\C-[[0;34m%SAt %s\C-[[44;37m%M%p\C-[[0;34m%S, Hit TAB for more, or the characters to insert%s\C-[[0;1;31m>>-\C-[[0m'
zstyle ':completion:*' list-separator /////////
zstyle ':completion:*' select-prompt $'\C-[[1;31m-<<\C-[[0;34m%SScrolling active: current selection at %s\C-[[37;44m%p\C-[[0;1;31m>>-\C-[[0m'
zstyle ':completion:*' squeeze-slashes on
zstyle ':completion:*' use-cache on
zstyle ':completion:*:("|''|)killall("|''|):*' command 'ps -o command'
zstyle ':completion:*:("|''|)slogin("|''|):*' hosts h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17 h18 h19 h20 host01.example.com host02.example.com host03.example.com host04.example.com host05.example.com host06.example.com host07.example.com host08.example.com host09.example.com host10.example.com 192.0.2.1 192.0.2.2 192.0.2.3 192.0.2.4 192.0.2.5 192.0.2.6 192.0.2.7 192.0.2.8
zstyle ':completion:*:("|''|)ssh("|''|):*' hosts h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17 h18 h19 h20 host01.example.com host02.example.com host03.example.com host04.example.com host05.example.com host06.example.com host07.example.com host08.example.com host09.example.com host10.example.com 192.0.2.1 192.0.2.2 192.0.2.3 192.0.2.4 192.0.2.5 192.0.2.6 192.0.2.7 192.0.2.8
zstyle ':completion:*:(fasd|fasd-file|zdir)' cache-policy zpwrDailyCachingPolicy
zstyle ':completion:*:*(git|git-checkout):*:files' list-colors '=(#b)(*)=1;30=1;32;43'
zstyle ':completion:*:*:("|''|)brew("|''|)-install:*:list' list-colors '=(#b)(*)=1;30=1;35;42'
zstyle ':completion:*:*:("|''|)brew("|''|):*:*:' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:("|''|)brew("|''|):*:all-commands' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:("|''|)brew("|''|):*:internal-commands' list-colors '=(#b)(*)=1;30=1;37;45'
zstyle ':completion:*:*:("|''|)brew-install("|''|):*:formulae' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:(f|z|zshz|zpwr-z|zpwr-gitzfordir|zpwr-gitzfordirmain|zpwr-gitzfordirdevelop|zm|zd|zg):*:*' cache-policy zpwrDailyCachingPolicy
zstyle ':completion:*:*:(se|see|seee|zsh-learn-Redo|rsql|re|zsh-learn-Searchl|zsh-learn-Searchle|zsh-learn-Searchlee|z|r|zsh-learn-Zsh-learn-get):*:*' sort false
zstyle ':completion:*:*:(zpwr-se|zpwr-see|zpwr-seee|zpwr-redo|zpwr-rsql|zpwr-re|zpwr-searchl|zpwr-searchle|zpwr-searchlee|zpwr-r|zpwr-get):*:*' sort false
zstyle ':completion:*:*:(zpwr-z|zpwr-gitzfordir|zpwr-gitzfordirmain|zpwr-gitzfordirdevelop|zm|zd|zg):*:*' sort off
zstyle ':completion:*:*:(zpwr-z|zpwr-gitzfordir|zpwr-gitzfordirmain|zpwr-gitzfordirdevelop|zm|zd|zg|z|zs):*:*' group-order options argument-rest globbed-files fasd-file fasd zdir files last-ten
zstyle ':completion:*:*:*:*:(zsh-learn-Zsh-learn-id|zsh-learn-Zsh-learn-text)' group-order zsh-learn-Zsh-learn-id zsh-learn-Zsh-learn-text
zstyle ':completion:*:*:*:*:*' menu 'select=0' interactive
zstyle ':completion:*:*:*:*:*:fasd' sort off
zstyle ':completion:*:*:*:*:*:zdir' sort off
zstyle ':completion:*:*:*:*:alias' list-colors '=(#b)(*)=1;30=34;42;4'
zstyle ':completion:*:*:*:*:aliases' list-colors '=(#b)(*)=1;30=34;42;4'
zstyle ':completion:*:*:*:*:ancillary-interrogator-commands' list-colors '=(#b)(*)=1;30=1;34;43;4'
zstyle ':completion:*:*:*:*:ancillary-manipulator-commands' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:attached-sessions' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:blob-objects' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:blobs' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:blobs-and-trees-in-treeish' list-colors '=(#b)(*)=1;30=1;34;43'
zstyle ':completion:*:*:*:*:builtins' list-colors '=(#b)(*)=1;30=1;37;4;43'
zstyle ':completion:*:*:*:*:cached-files' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:commands' list-colors '=(#b)(*)=1;37;45'
zstyle ':completion:*:*:*:*:commit-objects' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:commit-tags' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:commits' list-colors '=(#b)(*)=1;37;45'
zstyle ':completion:*:*:*:*:corrections' list-colors '=(#b)(*)=1;30=1;37;4;43'
zstyle ':completion:*:*:*:*:cpan-module' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:detached-sessions' list-colors '=(#b)(*)=1;30=1;37;45'
zstyle ':completion:*:*:*:*:executables' list-colors '=(#b)(*)=1;30=1;37;44'
zstyle ':completion:*:*:*:*:fasd' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:*:*:fasd-file' list-colors '=(#b)(*)=1;30=1;33;45'
zstyle ':completion:*:*:*:*:global-aliases' list-colors '=(#b)(*)=1;30=1;34;43;4'
zstyle ':completion:*:*:*:*:heads' list-colors '=(#b)(*)=1;30=34;42;4'
zstyle ':completion:*:*:*:*:heads-local' list-colors '=(#b)(*)=1;30=1;34;43;4'
zstyle ':completion:*:*:*:*:heads-remote' list-colors '=(#b)(*)=1;30=1;37;46'
zstyle ':completion:*:*:*:*:hosts' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:interaction-commands' list-colors '=(#b)(*)=1;30=1;37;41'
zstyle ':completion:*:*:*:*:last-clip' list-colors '=(#b)(*)=1;37;45'
zstyle ':completion:*:*:*:*:last-line' list-colors '=(#b)(*)=1;37;44'
zstyle ':completion:*:*:*:*:last-ten' list-colors '=(#b)(*)=1;33;45'
zstyle ':completion:*:*:*:*:main-porcelain-commands' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:manuals.0p' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:manuals.1' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:manuals.1p' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:manuals.2' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:*:*:manuals.3' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:manuals.3p' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:manuals.4' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:manuals.5' list-colors '=(#b)(*)=1;30=1;34;43;4'
zstyle ':completion:*:*:*:*:manuals.6' list-colors '=(#b)(*)=1;30=1;37;41'
zstyle ':completion:*:*:*:*:manuals.7' list-colors '=(#b)(*)=1;30=34;42;4'
zstyle ':completion:*:*:*:*:manuals.8' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:manuals.9' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:manuals.n' list-colors '=(#b)(*)=1;30=1;4;37;45'
zstyle ':completion:*:*:*:*:modified-files' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:*:*:named-directories' list-colors '=(#b)(*)=1;30=1;37;46'
zstyle ':completion:*:*:*:*:npm-cache' list-colors '=(#b)(*)=1;30=1;37;46'
zstyle ':completion:*:*:*:*:npm-search' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:options' list-colors '=(#b)([-<)(>]##)[ ]#([a-zA-Z0-9_.,~":?@#-]##)[ ]#([<)(>]#)[ ]#([a-zA-Z0-9+?.,()@3-]#)*=1;32=1;31=34=1;31=34'
zstyle ':completion:*:*:*:*:original' list-colors '=(#b)(*)=1;30=34;42;4'
zstyle ':completion:*:*:*:*:packages' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:parameters' list-colors '=(#b)(*)=1;30=1;32;45'
zstyle ':completion:*:*:*:*:plumbing-internal-helper-commands' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:plumbing-interrogator-commands' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:plumbing-manipulator-commands' list-colors '=(#b)(*)=1;30=34;42;4'
zstyle ':completion:*:*:*:*:plumbing-sync-commands' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:plumbing-sync-helper-commands' list-colors '=(#b)(*)=1;30=1;4;37;45'
zstyle ':completion:*:*:*:*:pname' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:prefixes' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:processes' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:processes-names' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:recent-branches' list-colors '=(#b)(*)=1;30=1;37;44'
zstyle ':completion:*:*:*:*:remote-branch-names-noprefix' list-colors '=(#b)(*)=1;30=1;33;46'
zstyle ':completion:*:*:*:*:remote-crate' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:remote-gem' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:remote-pip' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:*:*:*:revisions' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:*:*:s-providers' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:*:*:suffix-aliases' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:tags' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:third-party-commands' list-colors '=(#b)(*)=1;30=1;37;43'
zstyle ':completion:*:*:*:*:tmux' list-colors '=(#b)(*)=1;37;45'
zstyle ':completion:*:*:*:*:trees' list-colors '=(#b)(*)=1;30=1;34;41;4'
zstyle ':completion:*:*:*:*:user-commands' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:*:*:users' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:*:*:*:vtags' list-colors '=(#b)(*)=1;37;45'
zstyle ':completion:*:*:*:*:zdir' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*:*:zinit:*' group-name ''
zstyle ':completion:*:*:zpwr-gitedittag:*:*:commit-tags' sort off
zstyle ':completion:*:abs-directories' list-colors '=(#b)(*)=1;30=1;32;45'
zstyle ':completion:*:correct:*' insert-unambiguous on
zstyle ':completion:*:corrections' format $'\C-[[1;31m-<<\C-[[0;34m%d (errors: %e)\C-[[1;31m>>-\C-[[0m'
zstyle ':completion:*:descriptions' format $'\C-[[1;31m-<<\C-[[0;34m%d\C-[[1;31m>>-\C-[[0m'
zstyle ':completion:*:explanations' format $'\C-[[1;31m-<<\C-[[0;34m%d\C-[[1;31m>>-\C-[[0m'
zstyle ':completion:*:files' ignored-patterns '*.'
zstyle ':completion:*:functions' list-colors '=(#b)(*)=1;30=1;37;41'
zstyle ':completion:*:manuals' separate-sections on
zstyle ':completion:*:messages' format $'\C-[[1;31m-<<\C-[[0;34m%d\C-[[1;31m>>-\C-[[0m'
zstyle ':completion:*:reserved-words' list-colors '=(#b)(*)=1;30=1;4;37;45'
zstyle ':completion:*:warnings' format $'\C-[[1;31m-<<\C-[[0;34mNo Matches for %d\C-[[1;31m>>-\C-[[0m'
zstyle ':completion:*:zinit:argument-rest:plugins' list-colors '=(#b)(*)/(*)==1;35=1;33'
zstyle ':completion:*:zpwr-cd' list-colors '=(#b)(*)=1;30=1;37;42'
zstyle ':completion:*:zpwr-clean' list-colors '=(#b)(*)=1;30=1;4;37;45'
zstyle ':completion:*:zpwr-clipboard' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:zpwr-diag' list-colors '=(#b)(*)=1;30=1;33;44'
zstyle ':completion:*:zpwr-emacs' list-colors '=(#b)(*)=1;30=1;37;45'
zstyle ':completion:*:zpwr-forgit' list-colors '=(#b)(*)=1;30=34;42'
zstyle ':completion:*:zpwr-git' list-colors '=(#b)(*)=1;30=1;37;41'
zstyle ':completion:*:zpwr-github' list-colors '=(#b)(*)=1;30=1;4;37;45'
zstyle ':completion:*:zpwr-gitrepos' list-colors '=(#b)(*)=1;30=1;4;36;44'
zstyle ':completion:*:zpwr-learn' list-colors '=(#b)(*)=1;30=1;32;44'
zstyle ':completion:*:zpwr-log' list-colors '=(#b)(*)=1;30=1;32;45'
zstyle ':completion:*:zpwr-misc' list-colors '=(#b)(*)=1;30=37;46'
zstyle ':completion:*:zpwr-monitor' list-colors '=(#b)(*)=1;30=1;35;42'
zstyle ':completion:*:zpwr-regen' list-colors '=(#b)(*)=1;30=1;32;45'
zstyle ':completion:*:zpwr-search' list-colors '=(#b)(*)=1;30=1;34;43'
zstyle ':completion:*:zpwr-send' list-colors '=(#b)(*)=1;30=33;45'
zstyle ':completion:*:zpwr-travis' list-colors '=(#b)(*)=1;30=1;34;41'
zstyle ':completion:*:zpwr-update' list-colors '=(#b)(*)=1;30=1;37;46'
zstyle ':completion:*:zpwr-vim' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:zsh-learn-Zsh-learn-id' list-colors '=(#b)(*)=1;30=1;36;44'
zstyle ':completion:*:zsh-learn-Zsh-learn-text' list-colors '=(#b)(*)=1;30=1;34;43;4'
zstyle ':completion::*:(git-add|git-rm|less|rm|vi|vim|v):*' ignore-line on
zstyle ':completion:daily-cache:*' cache-policy zpwrDailyCachingPolicy
zstyle ':completion:fasd-complete-d:*' completer _fasd_zsh_word_complete_d
zstyle ':completion:fasd-complete-d:*' menu-select
zstyle ':completion:fasd-complete-f:*' completer _fasd_zsh_word_complete_f
zstyle ':completion:fasd-complete-f:*' menu-select
zstyle ':completion:fasd-complete:*' completer _fasd_zsh_word_complete
zstyle ':completion:fasd-complete:*' menu-select
zstyle ':fzf-tab:*' command fzf --ansi --ansi '--expect=$continuous_trigger' '--color=hl:$(( $#headers == 0 ? 108 : 255 ))' '--nth=2,3' '--delimiter=\x00' '--layout=reverse' '--height=${FZF_TMUX_HEIGHT:=100%}' '--tiebreak=begin' -m '--query=$query' '--header-lines=$#headers' --print-query --ansi '--expect=$continuous_trigger' '--color=hl:$(( $#headers == 0 ? 108 : 255 ))' '--nth=2,3' '--delimiter=\x00' '--layout=reverse' '--height=${FZF_TMUX_HEIGHT:=100%}' '--tiebreak=begin' -m '--query=$query' '--header-lines=$#headers' --print-query
zstyle ':fzf-tab:*' continuous-trigger /
zstyle ':fzf-tab:*' extra-opts
zstyle ':fzf-tab:*' fake-compadd default
zstyle ':fzf-tab:*' group-colors $'\C-[[94m' $'\C-[[32m' $'\C-[[33m' $'\C-[[35m' $'\C-[[31m' $'\C-[[38;5;27m' $'\C-[[36m' $'\C-[[38;5;100m' $'\C-[[38;5;98m' $'\C-[[91m' $'\C-[[38;5;80m' $'\C-[[92m' $'\C-[[38;5;214m' $'\C-[[38;5;165m' $'\C-[[38;5;124m' $'\C-[[38;5;120m'
zstyle ':fzf-tab:*' ignore false
zstyle ':fzf-tab:*' insert-space true
zstyle ':fzf-tab:*' no-group-color $'\C-[[37m'
zstyle ':fzf-tab:*' prefix
zstyle ':fzf-tab:*' print-query alt-enter
zstyle ':fzf-tab:*' query-string prefix input first
zstyle ':fzf-tab:*' show-group full
zstyle ':fzf-tab:*' single-group color header
zstyle ':vcs_info:*' actionformats '%b %F{1}| %a%f'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' formats %b%c%u%m
zstyle ':vcs_info:*' get-revision false
zstyle ':vcs_info:*' stagedstr ' '
zstyle ':vcs_info:*' unstagedstr ' '
zstyle ':vcs_info:git*+set-message:*' hooks vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname
zstyle ':vcs_info:hg*+gen-hg-bookmark-string:*' hooks hg-bookmarks
zstyle ':vcs_info:hg*+set-message:*' hooks vcs-detect-changes
zstyle ':vcs_info:hg*:*' branchformat ' %b'
zstyle ':vcs_info:hg*:*' get-bookmarks true
zstyle ':vcs_info:hg*:*' get-revision true
zstyle ':vcs_info:svn*+set-message:*' hooks vcs-detect-changes svn-detect-changes
zstyle ':vcs_info:svn*:*' actionformats '%c%u %F{1}| %a%f'
zstyle ':vcs_info:svn*:*' formats %c%u
zstyle -e ':completion:*:*:*:*:all-files' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle -e ':completion:*:*:*:*:directories' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle -e ':completion:*:*:*:*:files' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle -e ':completion:*:*:*:*:globbed-files' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle -e ':completion:*:*:*:*:local-directories' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle -e ':completion:*:*:f:*:*' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle -e ':completion:*:argument-rest:*' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)(*)==37;45=37;43=34}:${(s.:.)LS_COLORS}")'
zstyle :completion::megacomplete:zpwr-gitedittag::commit-tags sort off
zstyle :history-search-multi-word highlight-color 'bg=17'
zstyle :plugin:fast-syntax-highlighting theme default
zstyle :plugin:zconvey greeting none
zstyle :plugin:zconvey ls_after_rename 0
zstyle :plugin:zconvey output_method feeder
zstyle :plugin:zconvey use_zsystem_flock 1
zstyle :prezto:module:completion loaded 1
zstyle zle-hook types isearch-exit isearch-update line-pre-redraw line-init line-finish history-line-set keymap-select
zstyle zle-line-finish widgets 0:user:_zsh_highlight_widget_orig-s000-r000-zle-line-finish 1:.hist.format.hook
zstyle zle-line-init widgets 0:user:_zsh_highlight_widget_orig-s000-r000-zle-line-init 1:.hist.format.hook

# --- cache-policy -----------------------------------------------------
# Reproduced verbatim from zpwr's autoload/common/zpwrBindZstyle. Portable
# as-is: a `(Nm+N)` glob qualifier and nothing else. Returns 0 (rebuild)
# when the cache file is older than N days, which is what `_cache_invalid`
# tests. Exercising the real body keeps the `(Nm+N)` qualifier itself in
# the parity surface.
zpwrMonthlyCachingPolicy () {
    # rebuild if cache is more than a month old
    local -a oldp
    oldp=( "$1"(Nm+31) )
    (( $#oldp ))
}

zpwrWeeklyCachingPolicy () {
    # rebuild if cache is more than a week old
    local -a oldp
    oldp=( "$1"(Nm+7) )
    (( $#oldp ))
}

zpwrDailyCachingPolicy () {
    # rebuild if cache is more than a day old
    local -a oldp
    oldp=( "$1"(Nm+1) )
    (( $#oldp ))
}

# --- completers -------------------------------------------------------
# The real `_megacomplete` runs `\_complete` and returns its status, then
# adds tmux-pane words and a few other sources when the environment offers
# them. The delegation is the part the chain depends on, and it is
# reproducible; the extra sources need a live tmux pane, so they are left
# out rather than faked.
_megacomplete () {
    local ret
    \_complete && ret=0 || ret=1
    return ret
}

# fasd completers need a populated fasd database. With none, the honest
# result is "no matches", i.e. status 1 so the chain continues to
# `_approximate` / `_correct` exactly as it would when fasd has nothing to
# offer for this word.
_fasd_zsh_word_complete ()         { return 1 }
_fasd_zsh_word_complete_d ()       { return 1 }
_fasd_zsh_word_complete_f ()       { return 1 }
_fasd_zsh_word_complete_trigger () { return 1 }
