// AUTO-GENERATED. DO NOT EDIT BY HAND.
//
// Source: zsh upstream `/Users/wizard/forkedRepos/zsh/Doc/Zsh/params.yo`.
// Regen:  ./scripts/gen_option_docs.py --source specials /Users/wizard/forkedRepos/zsh/Doc/Zsh/params.yo > <this file>
// Generated: 2026-05-23

/// Canonical special variable name → markdown documentation body.
/// Pulled verbatim from every `item(tt(NAME))(...)` block in
/// the upstream yodl source. Use [`lookup_special_var_doc`] to resolve
/// case-insensitive lookups and any negated/compact aliases.
pub const SPECIAL_VAR_DOCS: &[(&str, &str)] = &[
    ("!", "The process ID of the last command started in the background with `&`,\nput into the background with the `bg` builtin, or spawned with `coproc`."),
    ("#", "The number of positional parameters in decimal.  Note that some confusion\nmay occur with the syntax `$#`_param_ which substitutes the length of\n_param_.  Use `${#}` to resolve ambiguities.  In particular, the\nsequence ``$#-`_..._' in an arithmetic expression is interpreted as\nthe length of the parameter `-`, q.v."),
    ("ARGC", "Same as `#`."),
    ("$", "The process ID of this shell, set when the shell initializes.  Processes\nforked from the shell without executing a new program, such as command\nsubstitutions and commands grouped with tt(LPAR())_..._tt(RPAR()),\nare subshells that duplicate the current shell, and thus substitute the\nsame value for `$$` as their parent shell."),
    ("-", "Flags supplied to the shell on invocation or by the `set`\nor `setopt` commands."),
    ("*", "An array containing the positional parameters."),
    ("argv", "Same as `*`.  Assigning to `argv` changes the local positional\nparameters, but `argv` is _not_ itself a local parameter.\nDeleting `argv` with `unset` in any function deletes it everywhere.\nThis can be avoided by declaring ``local +h argv`' before unsetting.\nEven when not so declared, only the innermost positional parameter\narray is deleted (so `*` and `@` in other scopes are not affected).\n\nA named reference to `argv` _does not_ permit a called function to\naccess the positional parameters of its caller."),
    ("@", "Same as `argv[@]`, even when `argv` is not set."),
    ("?", "The exit status returned by the last command."),
    ("0", "The name used to invoke the current shell, or as set by the `-c` command\nline option upon invocation.  If the `FUNCTION_ARGZERO` option is set,\n`$0` is set upon entry to a shell function to the name of the function,\nand upon entry to a sourced script to the name of the script, and reset to\nits previous value when the function or script returns."),
    ("status", "Same as `?`."),
    ("pipestatus", "An array containing the exit statuses returned by all commands in the\nlast pipeline."),
    ("_", "Initially, if `_` exists in the environment, then this parameter is set to\nits value. This value may be the full pathname of the current zsh\nexecutable or the script command file.\nLater, this parameter is set to the last argument of the previous command.\nAlso, this parameter is set in the environment of every command\nexecuted to the full pathname of the command."),
    ("CPUTYPE", "The machine type (microprocessor class or machine model),\nas determined at run time."),
    ("EGID", "The effective group ID of the shell process.  If you have sufficient\nprivileges, you may change the effective group ID of the shell\nprocess by assigning to this parameter.  Also (assuming sufficient\nprivileges), you may start a single command with a different\neffective group ID by `tt(LPAR()EGID=)_gid_tt(; command+RPAR())'\n\nIf this is made local, it is not implicitly set to 0, but may be\nexplicitly set locally."),
    ("EUID", "The effective user ID of the shell process.  If you have sufficient\nprivileges, you may change the effective user ID of the shell process\nby assigning to this parameter.  Also (assuming sufficient privileges),\nyou may start a single command with a different\neffective user ID by `tt(LPAR()EUID=)_uid_tt(; command+RPAR())'\n\nIf this is made local, it is not implicitly set to 0, but may be\nexplicitly set locally."),
    ("ERRNO", "The value of `errno` (see manref(errno)(3))\nas set by the most recently failed system call.\nThis value is system dependent and is intended for debugging\npurposes.  It is also useful with the `zsh/system` module which\nallows the number to be turned into a name or message.\n\nTo use this parameter, it must first be assigned a value (typically\n0 (zero)).  It is initially unset for scripting compatibility."),
    ("FUNCNEST", "Integer.  If greater than or equal to zero, the maximum nesting depth of\nshell functions.  When it is exceeded, an error is raised at the point\nwhere a function is called.  The default value is determined when\nthe shell is configured, but is typically 500.  Increasing\nthe value increases the danger of a runaway function recursion\ncausing the shell to crash.  Setting a negative value turns off\nthe check."),
    ("GID", "The real group ID of the shell process.  If you have sufficient privileges,\nyou may change the group ID of the shell process by assigning to this\nparameter.  Also (assuming sufficient privileges), you may start a single\ncommand under a different\ngroup ID by `tt(LPAR()GID=)_gid_tt(; command+RPAR())'\n\nIf this is made local, it is not implicitly set to 0, but may be\nexplicitly set locally."),
    ("HISTCMD", "The current history event number in an interactive shell, in other\nwords the event number for the command that caused `$HISTCMD`\nto be read.  If the current history event modifies the history,\n`HISTCMD` changes to the new maximum history event number."),
    ("HOST", "The current hostname."),
    ("LINENO", "The line number of the current line within the current script, sourced\nfile, or shell function being executed, whichever was started most\nrecently.  Note that in the case of shell functions the line\nnumber refers to the function as it appeared in the original definition,\nnot necessarily as displayed by the `functions` builtin."),
    ("LOGNAME", "If the corresponding variable is not set in the environment of the\nshell, it is initialized to the login name corresponding to the\ncurrent login session. This parameter is exported by default but\nthis can be disabled using the `typeset` builtin.  The value\nis set to the string returned by the manref(getlogin)(3) system call\nif that is available."),
    ("MACHTYPE", "The machine type (microprocessor class or machine model),\nas determined at compile time."),
    ("OLDPWD", "The previous working directory.  This is set when the shell initializes\nand whenever the directory changes."),
    ("OPTARG", "The value of the last option argument processed by the `getopts`\ncommand."),
    ("OPTIND", "The index of the last option argument processed by the `getopts`\ncommand."),
    ("OSTYPE", "The operating system, as determined at compile time."),
    ("PPID", "The process ID of the parent of the shell, set when the shell initializes.\nAs with `$$`, the value does not change in subshells created as a\nduplicate of the current shell."),
    ("PWD", "The present working directory.  This is set when the shell initializes\nand whenever the directory changes."),
    ("RANDOM", "A pseudo-random integer from 0 to 32767, newly generated each time\nthis parameter is referenced.  The random number generator\ncan be seeded by assigning a numeric value to `RANDOM`.\n\nThe values of `RANDOM` form an intentionally-repeatable pseudo-random\nsequence; subshells that reference `RANDOM` will result\nin identical pseudo-random values unless the value of `RANDOM` is\nreferenced or seeded in the parent shell in between subshell invocations.\n\n`RANDOM` uses the system's library function manref(rand)(3).\nIf higher degree of randomness is required, please consider using\nthe autoloadable parameter `SRANDOM` from\nifzman(the `zsh/random` module (see zmanref(zshmodules)))\\\nifnzman((The zsh/random Module))."),
    ("SECONDS", "The number of seconds since shell invocation.  On most platforms, this\nis a monotonic value, so it is not affected by NTP time jumps or other\nclock changes (though it may be affected by slewing).  If this parameter\nis assigned a value, then the value returned upon reference\nwill be the value that was assigned plus the number of seconds\nsince the assignment.\n\nUnlike other special parameters, the type of the `SECONDS` parameter can\nbe changed using the `typeset` command.  The type may be changed only\nto one of the floating point types or back to integer.  For example,\n``typeset -F SECONDS`'\ncauses the value to be reported as a floating point number.  The\nvalue is nominally available to nanosecond precision, although this\nvaries by platform (and probably isn't accurate to 1 ns regardless),\nand the shell may show more or fewer digits depending on the\nuse of `typeset`.  See\nthe documentation for the builtin `typeset` in\nnmref(Shell Builtin Commands)(zshbuiltins) for more details."),
    ("SHLVL", "Incremented by one each time a new shell is started."),
    ("signals", "An array containing the names of the signals.  Note that with\nthe standard zsh numbering of array indices, where the first element\nhas index 1, the signals are offset by 1 from the signal number\nused by the operating system.  For example, on typical Unix-like systems\n`HUP` is signal number 1, but is referred to as `$signals[2]`.  This\nis because of `EXIT` at position 1 in the array, which is used\ninternally by zsh but is not known to the operating system. On many systems\nthere is a block of reserved or unused signal numbers before the POSIX\nreal-time signals so the array index can't be used as an accurate indicator\nof their signal number. Use, for example, `kill -l SIGRTMIN` instead."),
    (".term.cursor", "The default color of the cursor.\n\nSee also the `.term.extensions` parameter."),
    (".term.bg", "The background color of the terminal if the terminal supports the\nnecessary interface for retrieving this information.\n\nSee also the `.term.extensions` parameter."),
    (".term.fg", "Like `.term.bg` but for the foreground color."),
    (".term.id", "Like the `TERM` parameter, this identifies the terminal but is obtained by\nquerying the terminal.  Many terminals name a different common terminal in\n`TERM` that they then emulate, often imperfectly.  This allows them to work\nwithout the need to distribute updates to terminal capability databases.  The\nmore accurate identification in this parameter may be useful when configuring\naspects of the shell differently for specific terminals.\n\nSee also the `.term.extensions` parameter."),
    (".term.version", "The version number of the terminal application, set in conjunction with\n`.term.id`."),
    (".term.mode", "Either `light` or `dark`.  In cases where the terminal background color is\ndetected and set in `.term.bg`, this is set to provide a basic indication of\nhow light that color is.  This may help with configuring readable color\ncombinations."),
    ("TRY_BLOCK_ERROR", "In an `always` block, indicates whether the preceding list of code\ncaused an error.  The value is 1 to indicate an error, 0 otherwise.\nIt may be reset, clearing the error condition.  See\nsectref(Complex Commands)(zshmisc)"),
    ("TRY_BLOCK_INTERRUPT", "This variable works in a similar way to `TRY_BLOCK_ERROR`, but\nrepresents the status of an interrupt from the signal SIGINT, which\ntypically comes from the keyboard when the user types `^C`.  If set to\n0, any such interrupt will be reset; otherwise, the interrupt is\npropagated after the `always` block.\n\nNote that it is possible that an interrupt arrives during the execution\nof the `always` block; this interrupt is also propagated."),
    ("TTY", "The name of the tty associated with the shell, if any."),
    ("TTYIDLE", "The idle time of the tty associated with the shell in seconds or -1 if there\nis no such tty."),
    ("UID", "The real user ID of the shell process.  If you have sufficient privileges,\nyou may change the user ID of the shell by assigning to this parameter.\nAlso (assuming sufficient privileges), you may start a single command\nunder a different\nuser ID by `tt(LPAR()UID=)_uid_tt(; command+RPAR())'\n\nIf this is made local, it is not implicitly set to 0, but may be\nexplicitly set locally."),
    ("USERNAME", "The username corresponding to the real user ID of the shell process.  If you\nhave sufficient privileges, you may change the username (and also the\nuser ID and group ID) of the shell by assigning to this parameter.\nAlso (assuming sufficient privileges), you may start a single command\nunder a different username (and user ID and group ID)\nby `tt(LPAR()USERNAME=)_username_tt(; command+RPAR())'"),
    ("VENDOR", "The vendor, as determined at compile time."),
    ("zsh_eval_context", "An array (colon-separated list) indicating the context of shell\ncode that is being run.  Each time a piece of shell code that\nis stored within the shell is executed a string is temporarily appended to\nthe array to indicate the type of operation that is being performed.\nRead in order the array gives an indication of the stack of\noperations being performed with the most immediate context last.\n\nNote that the variable does not give information on syntactic context such\nas pipelines or subshells.  Use `$ZSH_SUBSHELL` to detect subshells.\n\nThe context is one of the following:\nstartit__\nit_`cmdarg`_(\nCode specified by the `-c` option to the command line that invoked\nthe shell.\n)\nit_`cmdsubst`_(\nCommand substitution using of the ```_..._```,\ntt($+LPAR())_..._tt(RPAR()), `${{`_name_`}` _..._`}`,\n`${|`_..._`}`, or `${ `_..._` }` constructs.\n)\nit_`equalsubst`_(\nThe tt(=+LPAR())_..._tt(RPAR()) form of process substitution.\n)\nit_`eval`_(\nCode executed by the `eval` builtin.\n)\nit_`evalautofunc`_(\nCode executed with the `KSH_AUTOLOAD` mechanism in order to define\nan autoloaded function.\n)\nit_`fc`_(\nCode from the shell history executed by the `-e` option to the `fc`\nbuiltin.\n)\nit_`file`_(\nLines of code being read directly from a file, for example by\nthe `source` builtin.\n)\nit_`filecode`_(\nLines of code being read from a `.zwc` file instead of directly\nfrom the source file.\n)\nit_`globqual`_(\nCode executed by the `e` or `+` glob qualifier.\n)\nit_`globsort`_(\nCode executed to order files by the `o` glob qualifier.\n)\nit_`insubst`_(\nThe tt(<LPAR())_..._tt(RPAR()) form of process substitution.\n)\nit_`loadautofunc`_(\nCode read directly from a file to define an autoloaded function.\n)\nit_`outsubst`_(\nThe tt(>LPAR())_..._tt(RPAR()) form of process substitution.\n)\nit_`sched`_(\nCode executed by the `sched` builtin.\n)\nit_`shfunc`_(\nA shell function.\n)\nit_`stty`_(\nCode passed to `stty` by the `STTY` environment variable.\nNormally this is passed directly to the system's `stty` command,\nso this value is unlikely to be seen in practice.\n)\nit_`style`_(\nCode executed as part of a style retrieved by the `zstyle` builtin\nfrom the `zsh/zutil` module.\n)\nit_`toplevel`_(\nThe highest execution level of a script or interactive shell.\n)\nit_`trap`_(\nCode executed as a trap defined by the `trap` builtin.  Traps\ndefined as functions have the context `shfunc`.  As traps are\nasynchronous they may have a different hierarchy from other\ncode.\n)\nit_`zpty`_(\nCode executed by the `zpty` builtin from the `zsh/zpty` module.\n)\nit_`zregexparse-guard`_(\nCode executed as a guard by the `zregexparse` command from the\n`zsh/zutil` module.\n)\nit_`zregexparse-action`_(\nCode executed as an action by the `zregexparse` command from the\n`zsh/zutil` module.\n)\nendit__"),
    ("ZSH_ARGZERO", "If zsh was invoked to run a script, this is the name of the script.\nOtherwise, it is the name used to invoke the current shell.  This is\nthe same as the value of `$0` when the `POSIX_ARGZERO` option is\nset, but is always available."),
    ("ZSH_EXECUTION_STRING", "If the shell was started with the option `-c`, this contains\nthe argument passed to the option.  Otherwise it is not set."),
    ("ZSH_EXEPATH", "Full pathname of the executable file of the current zsh process."),
    ("ZSH_NAME", "Expands to the basename of the command used to invoke this instance\nof zsh."),
    ("ZSH_PATCHLEVEL", "The output of ``git describe --tags --long`' for the zsh repository\nused to build the shell.  This is most useful in order to keep\ntrack of versions of the shell during development between releases;\nhence most users should not use it and should instead rely on\n`$ZSH_VERSION`."),
    ("ZSH_SCRIPT", "If zsh was invoked to run a script, this is the name of the script,\notherwise it is unset."),
    ("ZSH_SUBSHELL", "Readonly integer.  Initially zero, incremented each time the shell forks\nto create a subshell for executing code.  Hence `tt((print $ZSH_SUBSHELL))'\nand `tt(print $(print $ZSH_SUBSHELL))' output 1, while\n`tt(( (print $ZSH_SUBSHELL) ))' outputs 2."),
    ("ZSH_VERSION", "The version number of the release of zsh."),
    ("ARGV0", "If exported, its value is used as the `argv[0]` of external commands.\nUsually used in constructs like ``ARGV0=emacs nethack`'."),
    ("BAUD", "The rate in bits per second at which data reaches the terminal.\nThe line editor will use this value in order to compensate for a slow\nterminal by delaying updates to the display until necessary.  If the\nparameter is unset or the value is zero the compensation mechanism is\nturned off.  The parameter is not set by default.\n\nThis parameter may be profitably set in some circumstances, e.g.\nfor slow modems dialing into a communications server, or on a slow wide\narea network.  It should be set to the baud\nrate of the slowest part of the link for best performance."),
    ("cdpath", "An array (colon-separated list)\nof directories specifying the search path for the `cd` command."),
    ("COLUMNS", "The number of columns for this terminal session.\nUsed for printing select lists and for the line editor."),
    ("CORRECT_IGNORE", "If set, is treated as a pattern during spelling correction.  Any\npotential correction that matches the pattern is ignored.  For example,\nif the value is ``_*`' then completion functions (which, by\nconvention, have names beginning with ``_`') will never be offered\nas spelling corrections.  The pattern does not apply to the correction\nof file names, as applied by the `CORRECT_ALL` option (so with the\nexample just given files beginning with ``_`' in the current\ndirectory would still be completed)."),
    ("CORRECT_IGNORE_FILE", "If set, is treated as a pattern during spelling correction of file names.\nAny file name that matches the pattern is never offered as a correction.\nFor example, if the value is ``.*`' then dot file names will never be\noffered as spelling corrections.  This is useful with the\n`CORRECT_ALL` option."),
    ("DIRSTACKSIZE", "The maximum size of the directory stack, by default there is no limit.  If the\nstack gets larger than this, it will be truncated automatically.\nThis is useful with the `AUTO_PUSHD` option.\npindex(AUTO_PUSHD, use of)"),
    ("ENV", "If the `ENV` environment variable is set when zsh is invoked as `sh`\nor `ksh`, `$ENV` is sourced after the profile scripts.  The value of\n`ENV` is subjected to parameter expansion, command substitution, and\narithmetic expansion before being interpreted as a pathname.  Note that\n`ENV` is _not_ used unless the shell is interactive and zsh is\nemulating **sh** or **ksh**."),
    ("FCEDIT", "The default editor for the `fc` builtin.  If `FCEDIT` is not set,\nthe parameter `EDITOR` is used; if that is not set either, a builtin\ndefault, usually `vi`, is used."),
    ("fignore", "An array (colon separated list)\ncontaining the suffixes of files to be ignored\nduring filename completion.  However, if completion only generates files\nwith suffixes in this list, then these files are completed anyway."),
    ("fpath", "An array (colon separated list)\nof directories specifying the search path for\nfunction definitions.  This path is searched when a function\nwith the `-u` attribute is referenced.  If an executable\nfile is found, then it is read and executed in the current environment."),
    ("histchars", "Three characters used by the shell's history and lexical analysis\nmechanism.  The first character signals the start of a history\nexpansion (default ``!`').  The second character signals the\nstart of a quick history substitution (default ``^`').  The third\ncharacter is the comment character (default ``#`').\n\nThe characters must be in the ASCII character set; any attempt to set\n`histchars` to characters with a locale-dependent meaning will be\nrejected with an error message."),
    ("HISTCHARS", "Same as `histchars`.  (Deprecated.)"),
    ("HISTFILE", "The file to save the history in when an interactive shell exits.\nIf unset, the history is not saved."),
    ("HISTORY_IGNORE", "If set, is treated as a pattern at the time history files are written.\nAny potential history entry that matches the pattern is skipped.  For\nexample, if the value is ``fc *`' then commands that invoke the\ninteractive history editor are never written to the history file.\n\nNote that `HISTORY_IGNORE` defines a single pattern: to\nspecify alternatives use the\n`tt(LPAR())_first_`|`_second_`|`_..._tt(RPAR())' syntax.\n\nCompare the `HIST_NO_STORE` option or the `zshaddhistory` hook,\neither of which would prevent such commands from being added to the\ninteractive history at all.  If you wish to use `HISTORY_IGNORE` to\nstop history being added in the first place, you can define the\nfollowing hook:\n\nexample(zshaddhistory+LPAR()RPAR() {\n  emulate -L zsh\n  ## uncomment if HISTORY_IGNORE\n  ## should use EXTENDED_GLOB syntax\n  # setopt extendedglob\n  [[ $1 != ${~HISTORY_IGNORE} ]]\n})"),
    ("HISTSIZE", "The maximum number of events stored in the internal history list.\nIf you use the `HIST_EXPIRE_DUPS_FIRST` option, setting this value\nlarger than the `SAVEHIST` size will give you the difference as a\ncushion for saving duplicated history events.\n\nIf this is made local, it is not implicitly set to 0, but may be\nexplicitly set locally."),
    ("HOME", "The default argument for the `cd` command.  This is not set automatically\nby the shell in `sh`, `ksh` or `csh` emulation, but it is typically\npresent in the environment anyway, and if it becomes set it has its usual\nspecial behaviour."),
    ("IFS", "Internal field separators (by default space, tab, newline and NUL), that\nare used to separate words which result from\ncommand or parameter expansion and words read by\nthe `read` builtin.  Any characters from the set space, tab and\nnewline that appear in the `IFS` are called _IFS white space_.\nOne or more IFS white space characters or one non-IFS white space\ncharacter together with any adjacent IFS white space character delimit\na field.  If an IFS white space character appears twice consecutively\nin the `IFS`, this character is treated as if it were not an IFS white\nspace character.\n\nIf the parameter is unset, the default is used.  Note this has\na different effect from setting the parameter to an empty string.\n\nIf `MULTIBYTE` option is on and `IFS` contains invalid characters in\nthe current locale, it is reset to the default."),
    ("KEYBOARD_HACK", "This variable defines a character to be removed from the end of the\ncommand line before interpreting it (interactive shells only). It is\nintended to fix the problem with keys placed annoyingly close to return\nand replaces the `SUNKEYBOARDHACK` option which did this for\nbackquotes only.  Should the chosen character be one of singlequote,\ndoublequote or backquote, there must also be an odd number of them\non the command line for the last one to be removed.\n\nFor backward compatibility, if the `SUNKEYBOARDHACK` option is\nexplicitly set, the value of `KEYBOARD_HACK` reverts to backquote.\nIf the option is explicitly unset, this variable is set to empty."),
    ("KEYTIMEOUT", "The time the shell waits, in hundredths of seconds, for another key to\nbe pressed when reading bound multi-character sequences."),
    ("LANG", "This variable determines the locale category for any category not\nspecifically selected via a variable starting with ``LC_`'."),
    ("LC_ALL", "This variable overrides the value of the ``LANG`' variable and the value\nof any of the other variables starting with ``LC_`'."),
    ("LC_COLLATE", "This variable determines the locale category for character collation\ninformation within ranges in glob brackets and for sorting."),
    ("LC_CTYPE", "This variable determines the locale category for character handling\nfunctions.  If the `MULTIBYTE` option is in effect this variable or\n`LANG` should contain a value that reflects the character set in\nuse, even if it is a single-byte character set, unless only the\n7-bit subset (ASCII) is used.  For example, if the character set\nis ISO-8859-1, a suitable value might be `en_US.iso88591` (certain\nLinux distributions) or `en_US.ISO8859-1` (MacOS)."),
    ("LC_MESSAGES", "This variable determines the language in which messages should be\nwritten.  Note that zsh does not use message catalogs."),
    ("LC_NUMERIC", "This variable affects the decimal point character and thousands\nseparator character for the formatted input/output functions\nand string conversion functions.  Note that zsh ignores this\nsetting when parsing floating point mathematical expressions."),
    ("LC_TIME", "This variable determines the locale category for date and time\nformatting in prompt escape sequences."),
    ("LINES", "The number of lines for this terminal session.\nUsed for printing select lists and for the line editor."),
    ("LISTMAX", "In the line editor, the number of matches to list without asking\nfirst. If the value is negative, the list will be shown if it spans at\nmost as many lines as given by the absolute value.\nIf set to zero, the shell asks only if the top of the listing would scroll\noff the screen."),
    ("MAIL", "If this parameter is set and `mailpath` is not set,\nthe shell looks for mail in the specified file."),
    ("MAILCHECK", "The interval in seconds between checks for new mail."),
    ("mailpath", "An array (colon-separated list) of filenames to check for\nnew mail.  Each filename can be followed by a ``?`' and a\nmessage that will be printed.  The message will undergo\nparameter expansion, command substitution and arithmetic\nexpansion with the variable `$_` defined as the name\nof the file that has changed.  The default message is\n``You have new mail`'.  If an element is a directory\ninstead of a file the shell will recursively check every\nfile in every subdirectory of the element."),
    ("manpath", "An array (colon-separated list)\nwhose value is not used by the shell.  The `manpath`\narray can be useful, however, since setting it also sets\n`MANPATH`, and vice versa."),
    ("module_path", "An array (colon-separated list)\nof directories that `zmodload`\nsearches for dynamically loadable modules.\nThis is initialized to a standard pathname,\nusually ``/usr/local/lib/zsh/$ZSH_VERSION`'.\n(The ``/usr/local/lib`' part varies from installation to installation.)\nFor security reasons, any value set in the environment when the shell\nis started will be ignored.\n\nThese parameters only exist if the installation supports dynamic\nmodule loading."),
    ("NULLCMD", "The command name to assume if a redirection is specified\nwith no command.  Defaults to `cat`.  For **sh**/**ksh**\nbehavior, change this to `:`.  For **csh**-like\nbehavior, unset this parameter; the shell will print an\nerror message if null commands are entered."),
    ("path", "An array (colon-separated list)\nof directories to search for commands.\nWhen this parameter is set, each directory is scanned\nand all files found are put in a hash table.\nDirectories named by relative path are not scanned for hashing."),
    ("POSTEDIT", "This string is output whenever the line editor exits.\nIt usually contains termcap strings to reset the terminal."),
    ("PROMPT4", "Same as `PS1`, `PS2`, `PS3` and `PS4`,\nrespectively."),
    ("prompt", "Same as `PS1`."),
    ("PROMPT_EOL_MARK", "When the `PROMPT_CR` and `PROMPT_SP` options are set, the\n`PROMPT_EOL_MARK` parameter can be used to customize how the end of\npartial lines are shown.  This parameter undergoes prompt expansion, with\nthe `PROMPT_PERCENT` option set.  If not set, the default behavior is\nequivalent to the value ``%B%S%#%s%b`'."),
    ("PS1", "The primary prompt string, printed before a command is read.\nIt undergoes a special form of expansion\nbefore being displayed; see sectref(Expansion of Prompt Sequences)(zshmisc).\nThe default is ``%m%# `'."),
    ("PS2", "The secondary prompt, printed when the shell needs more information\nto complete a command.\nIt is expanded in the same way as `PS1`.\nThe default is ``%_> `', which displays any shell constructs or quotation\nmarks which are currently being processed."),
    ("PS3", "Selection prompt used within a `select` loop.\nIt is expanded in the same way as `PS1`.\nThe default is ``?# `'."),
    ("PS4", "The execution trace prompt.  Default is `tt(PLUS()%N:%i> )', which displays\nthe name of the current shell structure and the line number within it.\nIn sh or ksh emulation, the default is `tt(PLUS() )'."),
    ("psvar", "An array (colon-separated list) whose elements can be used in\n`PROMPT` strings.  Setting `psvar` also sets `PSVAR`, and\nvice versa."),
    ("READNULLCMD", "The command name to assume if a single input redirection\nis specified with no command.  Defaults to `more`."),
    ("REPORTMEMORY", "If nonnegative, commands whose maximum resident set size (roughly\nspeaking, main memory usage) in kilobytes is greater than this\nvalue have timing statistics reported.  The format used to output\nstatistics is the value of the `TIMEFMT` parameter, which is the same\nas for the `REPORTTIME` variable and the `time` builtin; note that\nby default this does not output memory usage.  Appending\n`\" max RSS %M\"` to the value of `TIMEFMT` causes it to output the\nvalue that triggered the report.  If `REPORTTIME` is also in use,\nat most a single report is printed for both triggers.  This feature\nrequires the tt(getrusage+LPAR()RPAR()) system call, commonly supported by\nmodern Unix-like systems."),
    ("REPORTTIME", "If nonnegative, commands whose combined user and system execution times\n(measured in seconds) are greater than this value have timing\nstatistics printed for them.  Output is suppressed for commands\nexecuted within the line editor, including completion; commands\nexplicitly marked with the `time` keyword still cause the summary\nto be printed in this case."),
    ("REPLY", "This parameter is reserved by convention to pass string values between\nshell scripts and shell builtins in situations where a function call or\nredirection are impossible or undesirable.  The `read` builtin and the\n`select` complex command may set `REPLY`, and filename generation both\nsets and examines its value when evaluating certain expressions.  Some\nmodules also employ `REPLY` for similar purposes."),
    ("reply", "As `REPLY`, but for array values rather than strings."),
    ("RPS1", "This prompt is displayed on the right-hand side of the screen\nwhen the primary prompt is being displayed on the left.\nThis does not work if the `SINGLE_LINE_ZLE` option is set.\nIt is expanded in the same way as `PS1`."),
    ("RPS2", "This prompt is displayed on the right-hand side of the screen\nwhen the secondary prompt is being displayed on the left.\nThis does not work if the `SINGLE_LINE_ZLE` option is set.\nIt is expanded in the same way as `PS2`."),
    ("SAVEHIST", "The maximum number of history events to save in the history file.\n\nIf this is made local, it is not implicitly set to 0, but may be\nexplicitly set locally."),
    ("SPROMPT", "The prompt used for spelling correction.  The sequence\n``%R`' expands to the string which presumably needs spelling\ncorrection, and ``%r`' expands to the proposed correction.\nAll other prompt escapes are also allowed.\n\nThe actions available at the prompt are `[nyae]`:\nstartsit__\nsitem(`n` +LPAR()`no'+RPAR() +LPAR()default+RPAR())(Discard the correction.\nIf there are no more corrections, accept the command line, else (with\n`CORRECT_ALL`) prompt for the next.)\nsitem(`y` +LPAR()`yes'+RPAR())(Make the correction. If there are no more\ncorrections, accept the command line.)\nsitem(`a` +LPAR()`abort'+RPAR())(Place the entire command line in the\nhistory for later edit, but without accepting it.)\nsitem(`e` +LPAR()`edit'+RPAR())(Resume editing the command line.)\nendsit__"),
    ("STTY", "If this parameter is set in a command's environment, the shell runs the\n`stty` command with the value of this parameter as arguments in order to\nset up the terminal before executing the command. The modes apply only to the\ncommand, and are reset when it finishes or is suspended. If the command is\nsuspended and continued later with the `fg` or `wait` builtins it will\nsee the modes specified by `STTY`, as if it were not suspended.  This\n(intentionally) does not apply if the command is continued via ``kill\n-CONT`'.  `STTY` is ignored if the command is run in the background, or\nif it is in the environment of the shell but not explicitly assigned to in\nthe input line. This avoids running stty at every external command by\naccidentally exporting it. Also note that `STTY` should not be used for\nwindow size specifications; these will not be local to the command.\n\nIf the parameter is set and empty, all of the above applies except\nthat `stty` is not run. This can be useful as a way to freeze the tty\naround a single command, blocking its changes to tty settings,\nsimilar to the `ttyctl` builtin."),
    ("TERM", "The type of terminal in use.  This is used when looking up termcap\nsequences.  An assignment to `TERM` causes zsh to re-initialize the\nterminal, even if the value does not change (e.g., ``TERM=$TERM`').  It\nis necessary to make such an assignment upon any change to the terminal\ndefinition database or terminal type in order for the new settings to\ntake effect."),
    ("TERMINFO", "A reference to your terminfo database, used by the `terminfo' library when the\nsystem has it; see manref(terminfo)(5).\nIf set, this causes the shell to reinitialise the terminal, making the\nworkaround ``TERM=$TERM`' unnecessary."),
    ("TERMINFO_DIRS", "A colon-seprarated list of terminfo databases, used by the `terminfo' library\nwhen the system has it; see manref(terminfo)(5). This variable is only\nused by certain terminal libraries, in particular ncurses; see\nmanref(terminfo)(5) to check support on your system.  If set, this\ncauses the shell to reinitialise the terminal, making the workaround\n``TERM=$TERM`' unnecessary.  Note that unlike other colon-separated\narrays this is not tied to a zsh array."),
    (".term.extensions", "An array containing a list of extension features of the terminal.\nSee sectref(Terminal Extensions)(zshzle)."),
    (".term.querywait", "The time the shell waits, in hundredths of seconds, for the response to\nterminal queries.  A value of ``0'` disables the timeout and the shell will\nwait indefinitely.  If not set, a default of ``50'` or half a second is\nused."),
    ("TIMEFMT", "The format of process time reports with the `time` keyword.\nThe default is ``%J  %U user %S system %P cpu %*E total`'.\nRecognizes the following escape sequences, although not all\nmay be available on all systems, and some that are available\nmay not be useful:\n\nstartsit__\nsit_`%%`_(A ``%`'.)\nsit_`%U`_(CPU seconds spent in user mode.)\nsit_`%S`_(CPU seconds spent in kernel mode.)\nsit_`%E`_(Elapsed time in seconds.)\nsit_`%P`_(The CPU percentage, computed as\n100*(`%U`PLUS()`%S`)/`%E`.)\nsit_`%W`_(Number of times the process was swapped.)\nsit_`%X`_(The average amount in (shared) text space used in kilobytes.)\nsit_`%D`_(The average amount in (unshared) data/stack space used in\nkilobytes.)\nsit_`%K`_(The total space used (`%X`PLUS()`%D`) in kilobytes.)\nsit_`%M`_(The  maximum memory the process had in use at any time in\nkilobytes.)\nsit_`%F`_(The number of major page faults (page needed to be brought\nfrom disk).)\nsit_`%R`_(The number of minor page faults.)\nsit_`%I`_(The number of input operations.)\nsit_`%O`_(The number of output operations.)\nsit_`%r`_(The number of socket messages received.)\nsit_`%s`_(The number of socket messages sent.)\nsit_`%k`_(The number of signals received.)\nsit_`%w`_(Number of voluntary context switches (waits).)\nsit_`%c`_(Number of involuntary context switches.)\nsit_`%J`_(The name of this job.)\nendsit__\n\nA star may be inserted between the percent sign and flags printing time\n(e.g., ``%*E`'); this causes the time to be printed in\n`_hh_`:`_mm_`:`_ss_`.`_ttt_'\nformat (hours and minutes are only printed if they are not zero).\nAlternatively, ``m`', ``u`', or ``n`' may be used (e.g.,\n``%mE`') to produce time output in milliseconds, microseconds, or\nnanoseconds, respectively. Note that some timings on some platforms\nare not actually nanosecond-precise (nor accurate to 1 ns when\nthey are); in fact on many systems user and kernel times are not\neven microsecond-precise."),
    ("TMOUT", "If this parameter is nonzero, the shell will receive an `ALRM`\nsignal if a command is not entered within the specified number of\nseconds after issuing a prompt. If there is a trap on `SIGALRM`, it\nwill be executed and a new alarm is scheduled using the value of the\n`TMOUT` parameter after executing the trap.  If no trap is set, and\nthe idle time of the terminal is not less than the value of the\n`TMOUT` parameter, zsh terminates.  Otherwise a new alarm is\nscheduled to `TMOUT` seconds after the last keypress."),
    ("TMPPREFIX", "A pathname prefix which the shell will use for all temporary files.\nNote that this should include an initial part for the file name as\nwell as any directory names.  The default is ``/tmp/zsh`'."),
    ("TMPSUFFIX", "A filename suffix which the shell will use for temporary files created\nby process substitutions (e.g., `tt(=LPAR())_list_tt(RPAR())').\nNote that the value should include a leading dot ``.`' if intended\nto be interpreted as a file extension.  The default is not to append\nany suffix, thus this parameter should be assigned only when needed\nand then unset again."),
    ("WORDCHARS", "A list of non-alphanumeric characters considered part of a word\nby the line editor."),
    ("ZBEEP", "If set, this gives a string of characters, which can use all the same codes\nas the `bindkey` command as described in\nsectref(The zsh/zle Module)(zshmodules), that will be output to the terminal\ninstead of beeping.  This may have a visible instead of an audible effect;\nfor example, the string ``\\e[?5h\\e[?5l`' on a vt100 or xterm will have\nthe effect of flashing reverse video on and off (if you usually use reverse\nvideo, you should use the string ``\\e[?5l\\e[?5h`' instead).  This takes\nprecedence over the `NOBEEP` option."),
    ("ZDOTDIR", "The directory to search for shell startup files (.zshrc, etc),\nif not `$HOME`."),
    ("zle_bracketed_paste", "This two-element array contains the terminal escape sequences for enabling and\ndisabling the bracketed paste feature which allows ZLE to discern text that is\npasted into the terminal.  These escape sequences are used to enable bracketed\npaste when ZLE is active and disable it at other times.  Unsetting the\nparameter has the effect of ensuring that bracketed paste remains disabled.\nHowever, see also the `.term.extensions` parameter which provides a single\nplace to enable or disable terminal features."),
    ("zle_cursorform", "An array describing contexts in which ZLE should change the shape and color\nof the cursor.\nSee ifzman(_Cursor Shape and Color_ in zmanref(zshzle))\\\nifnzman((Cursor Shape and Color))."),
    ("zle_highlight", "An array describing contexts in which ZLE should highlight the input text.\nSee sectref(Character Highlighting)(zshzle)."),
    ("ZLE_LINE_ABORTED", "This parameter is set by the line editor when an error occurs.  It\ncontains the line that was being edited at the point of the error.\n``print -zr -- $ZLE_LINE_ABORTED`' can be used to recover the line.\nOnly the most recent line of this kind is remembered."),
    ("ZLE_SPACE_SUFFIX_CHARS", "These parameters are used by the line editor.  In certain circumstances\nsuffixes (typically space or slash) added by the completion system\nwill be removed automatically, either because the next editing command\nwas not an insertable character, or because the character was marked\nas requiring the suffix to be removed.\n\nThese variables can contain the sets of characters that will cause the\nsuffix to be removed.  If `ZLE_REMOVE_SUFFIX_CHARS` is set, those\ncharacters will cause the suffix to be removed; if\n`ZLE_SPACE_SUFFIX_CHARS` is set, those characters will cause the\nsuffix to be removed and replaced by a space.\n\nIf `ZLE_REMOVE_SUFFIX_CHARS` is not set, the default behaviour is\nequivalent to:\n\nexample(ZLE_REMOVE_SUFFIX_CHARS=$' \\t\\n;&|')\n\nIf `ZLE_REMOVE_SUFFIX_CHARS` is set but is empty, no characters have this\nbehaviour.  `ZLE_SPACE_SUFFIX_CHARS` takes precedence, so that the\nfollowing:\n\nexample(ZLE_SPACE_SUFFIX_CHARS=$'&|')\n\ncauses the characters ``&`' and ``|`' to remove the suffix but to\nreplace it with a space.\n\nTo illustrate the difference, suppose that the option `AUTO_REMOVE_SLASH`\nis in effect and the directory `DIR` has just been completed, with an\nappended `/`, following which the user types ``&`'.  The default result\nis ``DIR&`'.  With `ZLE_REMOVE_SUFFIX_CHARS` set but without including\n``&`' the result is ``DIR/&`'.  With `ZLE_SPACE_SUFFIX_CHARS` set to\ninclude ``&`' the result is ``DIR &`'.\n\nNote that certain completions may provide their own suffix removal\nor replacement behaviour which overrides the values described here.\nSee the completion system documentation in\nnmref(Completion System)(zshcompsys)."),
    ("ZLE_RPROMPT_INDENT", "If set, used to give the indentation between the right hand side of\nthe right prompt in the line editor as given by `RPS1` or `RPROMPT`\nand the right hand side of the screen.  If not set, the value 1 is used.\n\nTypically this will be used to set the value to 0 so that the prompt\nappears flush with the right hand side of the screen.  This is not the\ndefault as many terminals do not handle this correctly, in particular\nwhen the prompt appears at the extreme bottom right of the screen.\nRecent virtual terminals are more likely to handle this case correctly.\nSome experimentation is necessary."),
];

/// Alias → canonical mapping. One entry per surface name
/// that should resolve to the same documentation body.
pub const SPECIAL_VAR_ALIASES: &[(&str, &str)] = &[
    ("!", "!"),
    ("#", "#"),
    ("ARGC", "ARGC"),
    ("$", "$"),
    ("-", "-"),
    ("*", "*"),
    ("argv", "argv"),
    ("@", "@"),
    ("?", "?"),
    ("0", "0"),
    ("status", "status"),
    ("pipestatus", "pipestatus"),
    ("_", "_"),
    ("CPUTYPE", "CPUTYPE"),
    ("EGID", "EGID"),
    ("EUID", "EUID"),
    ("ERRNO", "ERRNO"),
    ("FUNCNEST", "FUNCNEST"),
    ("GID", "GID"),
    ("HISTCMD", "HISTCMD"),
    ("HOST", "HOST"),
    ("LINENO", "LINENO"),
    ("LOGNAME", "LOGNAME"),
    ("MACHTYPE", "MACHTYPE"),
    ("OLDPWD", "OLDPWD"),
    ("OPTARG", "OPTARG"),
    ("OPTIND", "OPTIND"),
    ("OSTYPE", "OSTYPE"),
    ("PPID", "PPID"),
    ("PWD", "PWD"),
    ("RANDOM", "RANDOM"),
    ("SECONDS", "SECONDS"),
    ("SHLVL", "SHLVL"),
    ("signals", "signals"),
    (".term.cursor", ".term.cursor"),
    (".term.bg", ".term.bg"),
    (".term.fg", ".term.fg"),
    (".term.id", ".term.id"),
    (".term.version", ".term.version"),
    (".term.mode", ".term.mode"),
    ("TRY_BLOCK_ERROR", "TRY_BLOCK_ERROR"),
    ("TRY_BLOCK_INTERRUPT", "TRY_BLOCK_INTERRUPT"),
    ("TTY", "TTY"),
    ("TTYIDLE", "TTYIDLE"),
    ("UID", "UID"),
    ("USERNAME", "USERNAME"),
    ("VENDOR", "VENDOR"),
    ("zsh_eval_context", "zsh_eval_context"),
    ("ZSH_EVAL_CONTEXT", "zsh_eval_context"),
    ("ZSH_ARGZERO", "ZSH_ARGZERO"),
    ("ZSH_EXECUTION_STRING", "ZSH_EXECUTION_STRING"),
    ("ZSH_EXEPATH", "ZSH_EXEPATH"),
    ("ZSH_NAME", "ZSH_NAME"),
    ("ZSH_PATCHLEVEL", "ZSH_PATCHLEVEL"),
    ("ZSH_SCRIPT", "ZSH_SCRIPT"),
    ("ZSH_SUBSHELL", "ZSH_SUBSHELL"),
    ("ZSH_SUBSHELL <S>", "ZSH_SUBSHELL"),
    ("ZSH_VERSION", "ZSH_VERSION"),
    ("ARGV0", "ARGV0"),
    ("BAUD", "BAUD"),
    ("cdpath", "cdpath"),
    ("CDPATH", "cdpath"),
    ("COLUMNS", "COLUMNS"),
    ("CORRECT_IGNORE", "CORRECT_IGNORE"),
    ("CORRECT_IGNORE_FILE", "CORRECT_IGNORE_FILE"),
    ("DIRSTACKSIZE", "DIRSTACKSIZE"),
    ("ENV", "ENV"),
    ("FCEDIT", "FCEDIT"),
    ("fignore", "fignore"),
    ("FIGNORE", "fignore"),
    ("fpath", "fpath"),
    ("FPATH", "fpath"),
    ("histchars", "histchars"),
    ("HISTCHARS", "HISTCHARS"),
    ("HISTFILE", "HISTFILE"),
    ("HISTORY_IGNORE", "HISTORY_IGNORE"),
    ("HISTSIZE", "HISTSIZE"),
    ("HOME", "HOME"),
    ("IFS", "IFS"),
    ("KEYBOARD_HACK", "KEYBOARD_HACK"),
    ("KEYTIMEOUT", "KEYTIMEOUT"),
    ("LANG", "LANG"),
    ("LC_ALL", "LC_ALL"),
    ("LC_COLLATE", "LC_COLLATE"),
    ("LC_CTYPE", "LC_CTYPE"),
    ("LC_MESSAGES", "LC_MESSAGES"),
    ("LC_NUMERIC", "LC_NUMERIC"),
    ("LC_TIME", "LC_TIME"),
    ("LINES", "LINES"),
    ("LISTMAX", "LISTMAX"),
    ("MAIL", "MAIL"),
    ("MAILCHECK", "MAILCHECK"),
    ("mailpath", "mailpath"),
    ("MAILPATH", "mailpath"),
    ("manpath", "manpath"),
    ("MANPATH", "manpath"),
    ("module_path", "module_path"),
    ("MODULE_PATH", "module_path"),
    ("NULLCMD", "NULLCMD"),
    ("path", "path"),
    ("PATH", "path"),
    ("POSTEDIT", "POSTEDIT"),
    ("PROMPT4", "PROMPT4"),
    ("PROMPT", "PROMPT4"),
    ("PROMPT2", "PROMPT4"),
    ("PROMPT3", "PROMPT4"),
    ("prompt", "prompt"),
    ("PROMPT_EOL_MARK", "PROMPT_EOL_MARK"),
    ("PS1", "PS1"),
    ("PS2", "PS2"),
    ("PS3", "PS3"),
    ("PS4", "PS4"),
    ("psvar", "psvar"),
    ("PSVAR", "psvar"),
    ("READNULLCMD", "READNULLCMD"),
    ("REPORTMEMORY", "REPORTMEMORY"),
    ("REPORTTIME", "REPORTTIME"),
    ("REPLY", "REPLY"),
    ("reply", "reply"),
    ("RPS1", "RPS1"),
    ("RPROMPT", "RPS1"),
    ("RPS2", "RPS2"),
    ("RPROMPT2", "RPS2"),
    ("SAVEHIST", "SAVEHIST"),
    ("SPROMPT", "SPROMPT"),
    ("STTY", "STTY"),
    ("TERM", "TERM"),
    ("TERMINFO", "TERMINFO"),
    ("TERMINFO_DIRS", "TERMINFO_DIRS"),
    (".term.extensions", ".term.extensions"),
    (".term.querywait", ".term.querywait"),
    ("TIMEFMT", "TIMEFMT"),
    ("TMOUT", "TMOUT"),
    ("TMPPREFIX", "TMPPREFIX"),
    ("TMPSUFFIX", "TMPSUFFIX"),
    ("WORDCHARS", "WORDCHARS"),
    ("ZBEEP", "ZBEEP"),
    ("ZDOTDIR", "ZDOTDIR"),
    ("zle_bracketed_paste", "zle_bracketed_paste"),
    ("zle_cursorform", "zle_cursorform"),
    ("zle_highlight", "zle_highlight"),
    ("ZLE_LINE_ABORTED", "ZLE_LINE_ABORTED"),
    ("ZLE_SPACE_SUFFIX_CHARS", "ZLE_SPACE_SUFFIX_CHARS"),
    ("ZLE_REMOVE_SUFFIX_CHARS", "ZLE_SPACE_SUFFIX_CHARS"),
    ("ZLE_RPROMPT_INDENT", "ZLE_RPROMPT_INDENT"),
];

/// Resolve a special variable name (case-insensitive, alias-aware)
/// to its canonical name + markdown body.
pub fn lookup_special_var_doc(name: &str) -> Option<(&'static str, &'static str)> {
    let key = name.to_string();
    let canon = SPECIAL_VAR_ALIASES
        .iter()
        .find(|(a, _)| *a == key.as_str())
        .map(|(_, c)| *c)?;
    SPECIAL_VAR_DOCS.iter().find(|(n, _)| *n == canon).map(|&(n, d)| (n, d))
}
