#!/usr/bin/env python3
"""comptab_parity.py — TAB-completion parity, run the way the shell is run.

Replaces the trust problems in compsys_parity.py:

  * Drives the NATIVE binary (`zshrs -f -i`) by default — the same path the
    user's daily shell takes (native `builtin_compinit`, SQLite/rkyv cache,
    `-C` worker-pool backfill). `--mode zsh` opts into `zshrs --zsh` for
    comparing the emulation path; it is NOT the default, because a green
    `--zsh` run says nothing about the binary that gets launched.
  * A divergence is a FAIL. Full stop. Re-running is only ever used to LABEL
    a failure `FLAKY`; it never converts one into a pass. Nondeterminism is a
    bug class (see the worker-pool tty race), not noise to average out.
  * A child that panics, dies, or never reaches a prompt is a FAIL with that
    reason — not a silently skipped case.
  * PS2 is left at its real `> ` value, so a shell that drops into a bogus
    continuation prompt shows it. (compsys_parity.py sets `PS2=''`, which
    renders that exact bug as an empty string.)
  * Both shells' raw PTY byte streams are scanned for panics and for
    diagnostics that appear on only one side.

Cases come from a corpus file (one command-line prefix per line, `#`
comments ignored) or the built-in list. Every case is `<buffer>` + TAB.

Usage:
    scripts/comptab_parity.py                       # built-in corpus
    scripts/comptab_parity.py --corpus cases.txt    # your own list
    scripts/comptab_parity.py --case 'wget -'       # one ad-hoc case
    scripts/comptab_parity.py --keys tab,tab        # keystrokes per case
    scripts/comptab_parity.py -v                    # print grids for passes too
    scripts/comptab_parity.py --mode zsh            # emulation path instead

Exit status: 0 only when every case is byte-identical.
"""

from __future__ import annotations

import argparse
import fcntl
import glob
import os
import pty
import select
import shlex
import signal
import struct
import sys
import tempfile
import termios
import time

try:
    import pyte
except ImportError:
    sys.exit("comptab_parity: pyte not installed (pip install pyte)")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SENTINEL = "@CT@"

KEYS = {
    "tab": b"\t",
    "btab": b"\x1b[Z",
    "up": b"\x1b[A",
    "down": b"\x1b[B",
    "cr": b"\r",
    "esc": b"\x1b",
    "ctrl-c": b"\x03",
}

# Panic / abort signatures either shell may emit onto its pty.
CRASH_MARKERS = (
    "panicked at",
    "capacity overflow",
    "RUST_BACKTRACE",
    "Segmentation fault",
    "Abort trap",
    "fatal runtime error",
)

BUILTIN_CORPUS = [
    "",              # command position
    "pr",            # partial command name — builtins + functions + externals
    "git ",
    "git chec",
    "git log --",
    "wget -",
    "curl -",
    "ssh -",
    "tar -",
    "find -",
    "grep -",
    "ls -",
    "chmod ",
    "kill -",
    "cd /",
    "man ",
    "echo $PA",
    "brew ",
    "cargo ",
    "rustup ",
    "npm ",
    "docker ",
    "tmux ",
    "ps -",
    "du -",
    "df -",
    "date -",
    "mkdir -",
    "cp -",
    "mv -",
    "rm -",
    "zsh -",
    "jq -",
    "unset ",
    "typeset -",
    "bindkey -",
    "zstyle ",
]


def resolve_dump(explicit):
    if explicit:
        return explicit
    home = os.path.expanduser("~")
    for pat in (
        os.path.join(home, ".zpwr/local/.zcompdump*"),
        os.path.join(home, ".zcompdump*"),
    ):
        hits = sorted(glob.glob(pat))
        if hits:
            return hits[0]
    return None


def user_fpath():
    """The fpath `zsh -f` sees on this host — the set the dump was built from."""
    import subprocess
    try:
        out = subprocess.run(
            ["zsh", "-f", "-c", "print -rl -- $fpath"],
            capture_output=True, text=True, timeout=10,
        ).stdout
        return [d for d in out.splitlines() if d and os.path.isdir(d)]
    except Exception:
        return []


def build_init(dump, fpath_dirs, zstyle_file):
    d = tempfile.mkdtemp(prefix="comptab_parity_")
    fpath_line = ""
    if fpath_dirs:
        fpath_line = "fpath=( %s )\n" % " ".join(shlex.quote(p) for p in fpath_dirs)
    zstyle_line = ""
    if zstyle_file and os.path.exists(zstyle_file):
        zstyle_line = "source %s\n" % shlex.quote(zstyle_file)
    if dump:
        compinit = "autoload -Uz compinit\ncompinit -C -d %s\n" % shlex.quote(dump)
    else:
        compinit = "autoload -Uz compinit\ncompinit -u\n"
    # PS1 is a fixed sentinel so both grids anchor identically. PS2 keeps its
    # real value on purpose: a shell that wrongly renders a continuation
    # prompt must show it in the diff.
    init = f"""\
# generated by comptab_parity.py
PROMPT='{SENTINEL} '
RPROMPT=''
PS2='> '
setopt no_beep
{fpath_line}{zstyle_line}{compinit}
print -u2 ''
"""
    path = os.path.join(d, "init.zsh")
    with open(path, "w") as f:
        f.write(init)
    return path


def child_env():
    env = {
        "TERM": "xterm-256color",
        "LANG": "C",
        "LC_ALL": "C",
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        # zshrs's autosuggest / syntax highlight have no zsh counterpart, so
        # their ghost text would diff on every case with a history hit. This
        # silences the fx LAYER only; the completion engine is untouched.
        "ZSHRS_NATIVE_ZLE_FX": "0",
        "RUST_BACKTRACE": "1",
    }
    if "HOME" in os.environ:
        env["HOME"] = os.environ["HOME"]
    return env


class Session:
    def __init__(self, argv, env, rows, cols, settle_ms):
        self.rows, self.cols = rows, cols
        self.settle = settle_ms / 1000.0
        self.screen = pyte.Screen(cols, rows)
        self.stream = pyte.ByteStream(self.screen)
        self.raw = bytearray()
        self.dead = False
        self.pid, self.fd = pty.fork()
        if self.pid == 0:
            os.execvpe(argv[0], argv, env)
        fcntl.ioctl(self.fd, termios.TIOCSWINSZ,
                    struct.pack("HHHH", rows, cols, 0, 0))

    def _read_once(self, timeout):
        r, _, _ = select.select([self.fd], [], [], timeout)
        if not r:
            return False
        try:
            data = os.read(self.fd, 65536)
        except OSError:
            self.dead = True
            return False
        if not data:
            self.dead = True
            return False
        self.raw.extend(data)
        self.stream.feed(data)
        return True

    def settle_out(self, max_wait=10.0, first_wait=6.0):
        start = last = time.monotonic()
        seen = False
        while True:
            now = time.monotonic()
            if now - start > max_wait:
                return
            got = self._read_once(0.05)
            now = time.monotonic()
            if got:
                seen, last = True, now
            elif not seen:
                if now - start > first_wait:
                    return
            elif now - last >= self.settle:
                return

    def wait_prompt(self, timeout=30.0):
        waited = 0.0
        while waited < timeout:
            self._read_once(0.05)
            if any(SENTINEL in line for line in self.screen.display):
                return True
            if self.dead:
                return False
            waited += 0.05
        return False

    def send(self, data):
        try:
            os.write(self.fd, data)
        except OSError:
            self.dead = True

    def clear(self):
        self.send(b"\x0c")
        self.settle_out(max_wait=3.0, first_wait=2.0)

    def grid(self):
        rows = [r.rstrip() for r in self.screen.display]
        while rows and rows[-1] == "":
            rows.pop()
        return rows

    def crashed(self):
        text = self.raw.decode("utf-8", "replace")
        return [m for m in CRASH_MARKERS if m in text]

    def alive(self):
        if self.dead:
            return False
        pid, _ = os.waitpid(self.pid, os.WNOHANG)
        return pid != self.pid

    def close(self):
        for b in (b"\x03", b"\x04"):
            try:
                os.write(self.fd, b)
            except OSError:
                pass
        try:
            os.close(self.fd)
        except OSError:
            pass
        for sig in (signal.SIGHUP, signal.SIGTERM, signal.SIGKILL):
            try:
                pid, _ = os.waitpid(self.pid, os.WNOHANG)
                if pid == self.pid:
                    return
                os.kill(self.pid, sig)
            except OSError:
                return
            for _ in range(20):
                try:
                    pid, _ = os.waitpid(self.pid, os.WNOHANG)
                    if pid == self.pid:
                        return
                except OSError:
                    return
                select.select([], [], [], 0.025)


class Result:
    """One shell's capture for one case."""

    def __init__(self, grid=None, reason=None, crash=None):
        self.grid = grid
        self.reason = reason      # None on success
        self.crash = crash or []


def capture(argv, env, args, init_file, buf, keys):
    sess = Session(argv, env, args.rows, args.cols, args.settle)
    try:
        sess.settle_out(max_wait=4.0, first_wait=3.0)
        sess.send(("source %s\n" % shlex.quote(init_file)).encode())
        if not sess.wait_prompt(timeout=args.boot_timeout):
            return Result(reason="never reached a prompt (boot/compinit hang or crash)",
                          crash=sess.crashed())
        sess.clear()
        if buf:
            sess.send(buf.encode())
            sess.settle_out(max_wait=3.0, first_wait=1.0)
        for k in keys:
            sess.send(KEYS.get(k, k.encode()))
            sess.settle_out(max_wait=15.0, first_wait=10.0)
        sess.settle_out(max_wait=3.0, first_wait=0.6)
        crash = sess.crashed()
        if crash:
            return Result(grid=sess.grid(), reason="crashed: " + ", ".join(crash),
                          crash=crash)
        if sess.dead:
            return Result(grid=sess.grid(), reason="shell exited mid-case")
        return Result(grid=sess.grid())
    finally:
        sess.close()


def diff_grids(ref, test):
    n = max(len(ref), len(test))
    out = []
    for i in range(n):
        a = ref[i] if i < len(ref) else "<absent>"
        b = test[i] if i < len(test) else "<absent>"
        if a != b:
            out.append((i, a, b))
    return out


def render(rows):
    return "\n".join("  %2d| %s" % (i, r) for i, r in enumerate(rows)) or "  <empty>"


def run_case(args, env, init_file, buf, keys):
    """Returns (status, detail) where status is PASS / FAIL / FLAKY.

    FLAKY is a FAIL that did not reproduce on the confirm run — reported as a
    failure with the nondeterminism called out, never scored as a pass.
    """
    ref = capture([args.zsh, "-f", "-i"], env, args, init_file, buf, keys)
    test = capture(args.test_argv, env, args, init_file, buf, keys)

    def judge(r, t):
        if r.reason:
            return "FAIL", "reference zsh: %s" % r.reason, r, t, None
        if t.reason:
            return "FAIL", "zshrs: %s" % t.reason, r, t, None
        d = diff_grids(r.grid, t.grid)
        if d:
            return "FAIL", "%d row(s) differ" % len(d), r, t, d
        return "PASS", "", r, t, []

    status, detail, r, t, diffs = judge(ref, test)
    if status == "PASS" or args.confirm == 0:
        return status, detail, r, t, diffs
    # Confirm ONLY to label nondeterminism. A pass on re-run means the case is
    # flaky, which is still a failure.
    for _ in range(args.confirm):
        r2 = capture([args.zsh, "-f", "-i"], env, args, init_file, buf, keys)
        t2 = capture(args.test_argv, env, args, init_file, buf, keys)
        s2, d2, rr, tt, dd = judge(r2, t2)
        if s2 == "PASS":
            return "FLAKY", detail + " (passed on re-run — nondeterministic)", r, t, diffs
    return status, detail, r, t, diffs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zshrs", default=os.path.join(REPO, "target", "debug", "zshrs"))
    ap.add_argument("--zsh", default="zsh")
    ap.add_argument("--mode", choices=("native", "zsh"), default="native",
                    help="native: run the zshrs binary as-is (default). "
                         "zsh: run it with --zsh (emulation path).")
    ap.add_argument("--dump", default=None)
    ap.add_argument("--no-dump", action="store_true")
    ap.add_argument("--zstyle", default=None, help="zstyle fixture sourced by both shells")
    ap.add_argument("--corpus", default=None, help="file of case buffers, one per line")
    ap.add_argument("--case", default=None, help="single ad-hoc case buffer")
    ap.add_argument("--keys", default="tab", help="comma-separated keys per case")
    ap.add_argument("--rows", type=int, default=40)
    ap.add_argument("--cols", type=int, default=110)
    ap.add_argument("--settle", type=int, default=300)
    ap.add_argument("--boot-timeout", type=float, default=40.0)
    ap.add_argument("--confirm", type=int, default=1,
                    help="re-runs used to LABEL a failure flaky (never to pass it)")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.zshrs):
        sys.exit("zshrs binary not found: %s (cargo build --bin zshrs)" % args.zshrs)
    args.test_argv = ([args.zshrs, "-f", "-i"] if args.mode == "native"
                      else [args.zshrs, "--zsh", "-f", "-i"])

    dump = None if args.no_dump else resolve_dump(args.dump)
    init_file = build_init(dump, user_fpath(), args.zstyle)
    env = child_env()
    keys = [k.strip() for k in args.keys.split(",") if k.strip()]

    if args.case is not None:
        cases = [args.case]
    elif args.corpus:
        with open(args.corpus) as f:
            cases = [l.rstrip("\n") for l in f
                     if l.strip() and not l.lstrip().startswith("#")]
    else:
        cases = BUILTIN_CORPUS

    print("# mode   : %s (%s)" % (args.mode, " ".join(args.test_argv)))
    print("# dump   : %s" % (dump or "<none>"))
    print("# init   : %s" % init_file)
    print("# geom   : %dx%d  settle=%dms  keys=%s" %
          (args.rows, args.cols, args.settle, "+".join(keys)))
    print("# cases  : %d" % len(cases))
    print()

    passed = 0
    failures = []
    for buf in cases:
        status, detail, ref, test, diffs = run_case(args, env, init_file, buf, keys)
        label = "%-6s %r" % (status, buf)
        print(label + (("  (%s)" % detail) if detail else ""))
        sys.stdout.flush()
        if status == "PASS":
            passed += 1
            if args.verbose:
                print(render(test.grid))
            continue
        failures.append((buf, status, detail, ref, test, diffs))
        print("  --- zsh (ref) ---")
        print(render(ref.grid or []))
        print("  --- zshrs ---")
        print(render(test.grid or []))
        if diffs:
            print("  --- row diffs ---")
            for i, a, b in diffs[:12]:
                print("  row %2d: zsh  = %r" % (i, a))
                print("          zshrs= %r" % (b,))
        print()

    print("\n# %d passed, %d failed, %d total" % (passed, len(failures), len(cases)))
    if failures:
        print("# failing cases: " + ", ".join(repr(f[0]) for f in failures))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
