#!/usr/bin/env python3
"""gen_parity_combos.py — derive the zstyle combo fixtures from the live one.

    scripts/gen_parity_combos.py            # regenerate scripts/parity_combos/

The combos used to be hand-maintained copies of the full fixture with a few
lines deleted, so every refresh of `parity_zstyle.zsh` left them stale. They
are now DERIVED: each combo is the current fixture with one axis removed (or
one axis forced to a specific value), which is what isolates a rendering
difference to a single style.

Two shapes:

  drop-<axis>   the full config minus every statement setting that style.
                Answers "does the divergence need this style to be set?"
  force-<name>  the full config plus an override pinning one style to a value.
                Answers "does it need this style set to THIS value?" — not the
                same question, since unset and set-to-off differ for styles
                whose compsys default is on.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = os.path.join(REPO, "scripts", "parity_zstyle.zsh")
OUTDIR = os.path.join(REPO, "scripts", "parity_combos")

# axis name -> style name(s) whose statements get dropped
DROP_AXES: dict[str, tuple[str, ...]] = {
    "menu": ("menu",),
    "format": ("format", "auto-description"),
    "listcolors": ("list-colors",),
    "listprompt": ("list-prompt",),
    "selectprompt": ("select-prompt",),
    "groupname": ("group-name", "group-order"),
    "verbose": ("verbose", "extra-verbose"),
    "matcherlist": ("matcher-list", "matcher"),
    "completer": ("completer",),
    "listpacked": ("list-packed", "list-rows-first", "list-grouped"),
    "acceptexact": ("accept-exact", "accept-exact-dirs"),
    "squeezeslashes": ("squeeze-slashes",),
    "specialdirs": ("special-dirs",),
    "ignored": ("ignored-patterns", "ignore-parents", "ignore-line"),
    "insertunambiguous": ("insert-unambiguous", "original", "prompt"),
    "hosts": ("hosts", "users", "users-hosts"),
    "cache": ("use-cache", "cache-path", "cache-policy"),
}

# combo name -> zstyle lines appended AFTER the full fixture
FORCE_COMBOS: dict[str, tuple[str, ...]] = {
    "menu-select": ("zstyle ':completion:*' menu select",),
    # `interactive` puts the menuselect keymap into filter mode: printable
    # characters narrow the list instead of self-inserting. Without this combo
    # the menusel_* sequences never reach that keymap at all.
    "menu-select-interactive": ("zstyle ':completion:*' menu select interactive",),
    "menu-select-search": ("zstyle ':completion:*' menu select search",),
    "menu-off": ("zstyle ':completion:*' menu no",),
    "menu-yes-eq-2": ("zstyle ':completion:*' menu yes=2",),
    "listpacked-on": ("zstyle ':completion:*' list-packed true",),
    "listpacked-off": ("zstyle ':completion:*' list-packed false",),
    "rowsfirst-on": ("zstyle ':completion:*' list-rows-first true",),
    "groupname-off": ("zstyle ':completion:*' group-name",),
    "verbose-off": ("zstyle ':completion:*' verbose false",),
    "no-descriptions": ("zstyle ':completion:*:descriptions' format ''",),
    "single-completer": ("zstyle ':completion:*' completer _complete",),
    "complete-then-approximate": (
        "zstyle ':completion:*' completer _complete _approximate",
    ),
    "matcher-caseless": (
        "zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'",
    ),
    "matcher-none": ("zstyle ':completion:*' matcher-list ''",),
}

# A deliberately tiny config: the two styles that most change list shape.
MINIMAL = (
    "zstyle ':completion:*:descriptions' format '-<<%d>>-'",
    "zstyle ':completion:*' group-name ''",
)

HEADER = """\
# GENERATED by scripts/gen_parity_combos.py — do not hand-edit.
# Source fixture: scripts/parity_zstyle.zsh
# {what}
"""


def statements(path: str) -> list[str]:
    return [l.rstrip("\n") for l in open(path) if l.startswith("zstyle ")]


def style_of(stmt: str) -> str | None:
    """The style NAME in a `zstyle <context> <style> [values...]` statement.

    The context is quoted (`':completion:*'`) or a bare word; the style is the
    token right after it. `-e`/`-L`-style flags are not emitted by `zstyle -L`
    for value statements, so a positional split is enough.
    """
    m = re.match(r"^zstyle\s+(?:'[^']*'|\"[^\"]*\"|\S+)\s+(\S+)", stmt)
    return m.group(1) if m else None


def write(outdir: str, name: str, what: str, lines: list[str]) -> None:
    path = os.path.join(outdir, f"{name}.zsh")
    with open(path, "w") as f:
        f.write(HEADER.format(what=what))
        f.write("\n".join(lines) + "\n")
        # `statements()` keeps only lines starting with "zstyle ", so the
        # fixture's own `source parity_zstyle_stubs.zsh` line never reaches a
        # combo. Without it every one of these files — `full.zsh` included,
        # which claims to be the complete live config — names
        # zpwrMonthlyCachingPolicy / _megacomplete / _fasd_zsh_word_complete*
        # in a function-valued style without defining them, and compsys
        # quietly takes a different path: an unknown completer is skipped and
        # a missing cache-policy reads as "always rebuild". Emit it here so
        # every combo is self-contained. `${(%):-%x}` (the file being
        # sourced) rather than `$0`: `$0` is only the script path when
        # FUNCTION_ARGZERO is set, and with it unset `:A` resolves the
        # bare shell name against $PWD and the source silently misses.
        f.write(
            "\n# Definitions for the non-zsh functions the styles above name.\n"
            "source ${${(%):-%x}:A:h}/../parity_zstyle_stubs.zsh\n"
        )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fixture", default=FIXTURE)
    ap.add_argument("--outdir", default=OUTDIR)
    args = ap.parse_args()

    if not os.path.exists(args.fixture):
        sys.exit(f"fixture not found: {args.fixture}")
    os.makedirs(args.outdir, exist_ok=True)
    outdir = args.outdir

    base = statements(args.fixture)
    written = []

    write(outdir, "full", "the complete live config, unmodified", base)
    written.append(("full", len(base)))

    write(outdir, "minimal", "only the two list-shaping styles", list(MINIMAL))
    written.append(("minimal", len(MINIMAL)))

    write(outdir, "none", "no styles at all — compsys defaults", [])
    written.append(("none", 0))

    for axis, style_names in DROP_AXES.items():
        kept = [s for s in base if style_of(s) not in style_names]
        dropped = len(base) - len(kept)
        if dropped == 0:
            # Nothing in the live config sets it, so the combo would be a
            # duplicate of `full`. Say so rather than emitting a decoy.
            print(f"  skip drop-{axis}: live config sets none of {style_names}")
            continue
        write(outdir, f"drop-{axis}",
              f"full config minus every `{'`/`'.join(style_names)}` statement "
              f"({dropped} dropped)",
              kept)
        written.append((f"drop-{axis}", len(kept)))

    for name, extra in FORCE_COMBOS.items():
        write(outdir, f"force-{name}",
              f"full config, then `{extra[0]}`",
              base + ["", "# forced axis"] + list(extra))
        written.append((f"force-{name}", len(base) + len(extra)))

    print(f"{len(written)} combo(s) in {outdir}:")
    for name, n in written:
        print(f"  {name:28s} {n:4d} statement(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
