#!/usr/bin/env python3
"""Regenerate the canonical-grammar tables in the free public docs/index.html
from data/grammar/canonical.json.

    docs/index.html   <!-- BEGIN CANONICAL-GRAMMAR -->
                      <!-- END   CANONICAL-GRAMMAR -->

The paid reference manual (docs/reference.{html,tex}) is generated by the copy
of this script in the private menke-books repo. Re-run after editing
canonical.json.
"""
from __future__ import annotations

import html
import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANON = ROOT / "data" / "grammar" / "canonical.json"
HTML_FILES = [
    ROOT / "docs" / "index.html",
]

BEGIN_HTML = "<!-- BEGIN CANONICAL-GRAMMAR -->"
END_HTML = "<!-- END CANONICAL-GRAMMAR -->"


# ── HTML rendering ──────────────────────────────────────────────────
HTML_STYLE = """<style>
.cg-section { margin: 1.4rem 0; }
.cg-section h3 { font-family: 'Orbitron', sans-serif; font-size: 13px; font-weight: 700; letter-spacing: 1.5px; text-transform: uppercase; color: var(--cyan); margin: 1.1rem 0 0.4rem; border-bottom: 1px dashed var(--border); padding-bottom: 0.25rem; }
.cg-section .cg-meta { font-size: 11px; color: var(--text-muted); letter-spacing: 0.5px; margin: 0 0 0.6rem; }
.cg-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(8.5rem, 1fr)); gap: 4px 10px; margin: 0.4rem 0 1rem; }
.cg-grid code { font-family: 'Share Tech Mono', ui-monospace, monospace; font-size: 11.5px; color: var(--accent-light); background: var(--bg); padding: 1px 5px; border-left: 2px solid var(--cyan); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.cg-grid code:hover { background: var(--bg-hover); color: var(--text); }
.cg-table { width: 100%; border-collapse: collapse; margin: 0.4rem 0 1rem; font-size: 12px; }
.cg-table th { background: var(--bg-secondary); color: var(--cyan); font-family: 'Orbitron', sans-serif; font-size: 10px; font-weight: 700; letter-spacing: 1.2px; text-transform: uppercase; text-align: left; padding: 6px 10px; border: 1px solid var(--border); }
.cg-table td { padding: 5px 10px; border: 1px solid var(--border); color: var(--text-dim); vertical-align: top; }
.cg-table td:first-child { white-space: nowrap; font-family: 'Share Tech Mono', monospace; color: var(--accent-light); font-weight: 600; }
.cg-table td code { color: var(--accent-light); background: var(--bg); padding: 1px 4px; font-size: 11px; }
.cg-table tr:hover td { background: var(--bg-hover); }
.cg-counts { display: grid; grid-template-columns: repeat(auto-fill, minmax(9rem, 1fr)); gap: 0.8rem; margin: 1rem 0; text-align: center; }
.cg-counts .cg-val { font-family: 'Orbitron', sans-serif; font-size: 24px; font-weight: 900; color: var(--cyan); }
.cg-counts .cg-lab { font-size: 9.5px; color: var(--text-muted); letter-spacing: 1.5px; text-transform: uppercase; margin-top: 0.2rem; }
</style>"""


def h(s: str) -> str:
    return html.escape(s, quote=False)


def render_html(data: dict) -> str:
    today = date.today().isoformat()
    parts = [BEGIN_HTML, "<!-- generated by scripts/gen_grammar_docs.py -->"]
    parts.append(HTML_STYLE)

    # Counts strip
    counts = [
        ("Keywords", len(data["keywords"])),
        ("Builtins", len(data["core_builtins"])
            + len(data["module_builtins"])
            + len(data["zshrs_ext_builtins"])),
        ("Options", len(data["options"])),
        ("Special vars", len(data["special_vars"])),
        ("Param flags", len(data["param_flags"])),
        ("Glob quals", len(data["glob_qualifiers"])),
        ("Operators", len(data["operators"])),
        ("History exp.", len(data["history_expansions"])),
        ("Modifiers", len(data["modifiers"])),
    ]
    parts.append("<div class=\"cg-counts\">")
    for label, n in counts:
        parts.append(
            f"  <div><div class=\"cg-val\">{n:,}</div>"
            f"<div class=\"cg-lab\">{h(label)}</div></div>"
        )
    parts.append("</div>")
    parts.append(f"<p class=\"docs-build-line\">Generated {today} from "
                 "<code>data/grammar/canonical.json</code>.</p>")

    # Keywords by category
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Reserved keywords ({len(data['keywords'])})</h3>")
    parts.append("<p class=\"cg-meta\">Source: <code>src/zsh/Src/hashtable.c::reswds[]</code> + zshrs lexer extensions.</p>")
    by_cat: dict[str, list[str]] = {}
    for e in data["keywords"]:
        by_cat.setdefault(e["category"], []).append(e["name"])
    cat_labels = {
        "control": "Control flow", "decl": "Declaration", "fn": "Function",
        "loop": "Loop control", "modifier": "Modifier (precommand)",
        "io": "I/O / source", "grouping": "Grouping", "operator": "Operator-like",
    }
    for cat, names in sorted(by_cat.items()):
        label = cat_labels.get(cat, cat)
        parts.append(f"<h4 style=\"margin:0.7rem 0 0.3rem;color:var(--accent);font-size:11px;letter-spacing:1px;text-transform:uppercase;\">{h(label)} ({len(names)})</h4>")
        parts.append("<div class=\"cg-grid\">")
        for n in sorted(names):
            parts.append(f"  <code>{h(n)}</code>")
        parts.append("</div>")
    parts.append("</div>")

    # Builtins — split into 3 sub-sections
    builtin_sources = [
        ("core_builtins", "POSIX / zsh core",
            "Source: <code>src/zsh/Src/builtin.c::builtins[]</code>."),
        ("module_builtins", "zsh modules",
            "Source: <code>src/zsh/Src/Modules/*.c</code> (curses, datetime, pcre, files, stat, terminfo, zftp, zselect, zsystem, zutil, …)."),
        ("zshrs_ext_builtins", "zshrs extensions",
            "Source: <code>daemon/builtins.rs</code> + <code>src/extensions/ext_builtins.rs</code>."),
    ]
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Builtins ({sum(len(data[k]) for k, _, _ in builtin_sources)})</h3>")
    parts.append("<p class=\"cg-meta\">Every command implemented inside the shell — no fork/exec required.</p>")
    for key, label, meta in builtin_sources:
        items = sorted(e["name"] for e in data[key])
        parts.append(f"<h4 style=\"margin:0.7rem 0 0.3rem;color:var(--accent);font-size:11px;letter-spacing:1px;text-transform:uppercase;\">{h(label)} ({len(items)})</h4>")
        parts.append(f"<p class=\"cg-meta\">{meta}</p>")
        parts.append("<div class=\"cg-grid\">")
        for n in items:
            parts.append(f"  <code>{h(n)}</code>")
        parts.append("</div>")
    parts.append("</div>")

    # Options
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>setopt options ({len(data['options'])})</h3>")
    parts.append("<p class=\"cg-meta\">Source: <code>src/zsh/Src/options.c::optns[]</code>. "
                 "All upstream zsh options recognized by name; use <code>setopt</code> / "
                 "<code>unsetopt</code> to toggle, or <code>NO_</code> prefix (e.g. <code>NO_GLOB</code>).</p>")
    parts.append("<div class=\"cg-grid\">")
    for e in sorted(data["options"], key=lambda d: d["name"]):
        parts.append(f"  <code>{h(e['name'].upper())}</code>")
    parts.append("</div>")
    parts.append("</div>")

    # Special vars
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Special variables ({len(data['special_vars'])})</h3>")
    parts.append("<p class=\"cg-meta\">Source: <code>src/zsh/Src/params.c::special_params[]</code>. "
                 "Includes scalar (<code>$?</code>, <code>$RANDOM</code>) and array forms "
                 "(<code>$path</code>, <code>$pipestatus</code>); upper-case and lower-case names "
                 "are linked pairs where applicable.</p>")
    parts.append("<div class=\"cg-grid\">")
    for e in sorted(data["special_vars"], key=lambda d: d["name"]):
        n = e["name"]
        # use $ prefix for display
        parts.append(f"  <code>${h(n)}</code>")
    parts.append("</div>")
    parts.append("</div>")

    # Parameter flags
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Parameter expansion flags ({len(data['param_flags'])})</h3>")
    parts.append("<p class=\"cg-meta\">Single-letter modifiers inside <code>${(X)var}</code>. "
                 "Composable: <code>${(jL)arr}</code> = join lowercase.</p>")
    parts.append("<table class=\"cg-table\">")
    parts.append("  <thead><tr><th>Flag</th><th>Meaning</th></tr></thead>")
    parts.append("  <tbody>")
    for e in data["param_flags"]:
        parts.append(f"    <tr><td><code>${{({h(e['flag'])})var}}</code></td>"
                     f"<td>{h(e['doc'])}</td></tr>")
    parts.append("  </tbody>")
    parts.append("</table>")
    parts.append("</div>")

    # Glob qualifiers
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Glob qualifiers ({len(data['glob_qualifiers'])})</h3>")
    parts.append("<p class=\"cg-meta\">Modifiers inside <code>*(X)</code>. Composable; "
                 "use <code>^</code> to negate the group, <code>,</code> to OR-combine groups.</p>")
    parts.append("<table class=\"cg-table\">")
    parts.append("  <thead><tr><th>Qual</th><th>Meaning</th></tr></thead>")
    parts.append("  <tbody>")
    for e in data["glob_qualifiers"]:
        parts.append(f"    <tr><td><code>*({h(e['sym'])})</code></td>"
                     f"<td>{h(e['doc'])}</td></tr>")
    parts.append("  </tbody>")
    parts.append("</table>")
    parts.append("</div>")

    # Operators
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Operators / redirections / substitution forms ({len(data['operators'])})</h3>")
    parts.append("<p class=\"cg-meta\">Lexer-recognized tokens. Grouped by <code>kind</code>: "
                 "pipeline / list / case / redirect / procsub / subst / arith / cond / "
                 "assign / compare / glob / tilde / brace / expansion / string / extension.</p>")
    parts.append("<table class=\"cg-table\">")
    parts.append("  <thead><tr><th>Symbol</th><th>Kind</th><th>Meaning</th></tr></thead>")
    parts.append("  <tbody>")
    for e in data["operators"]:
        parts.append(f"    <tr><td><code>{h(e['sym'])}</code></td>"
                     f"<td>{h(e['kind'])}</td>"
                     f"<td>{h(e['doc'])}</td></tr>")
    parts.append("  </tbody>")
    parts.append("</table>")
    parts.append("</div>")

    # History expansions
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>History expansions ({len(data['history_expansions'])})</h3>")
    parts.append("<p class=\"cg-meta\">Recall previous commands / words. Lexer-stage expansion before parsing.</p>")
    parts.append("<table class=\"cg-table\">")
    parts.append("  <thead><tr><th>Form</th><th>Meaning</th></tr></thead>")
    parts.append("  <tbody>")
    for e in data["history_expansions"]:
        parts.append(f"    <tr><td><code>{h(e['sym'])}</code></td>"
                     f"<td>{h(e['doc'])}</td></tr>")
    parts.append("  </tbody>")
    parts.append("</table>")
    parts.append("</div>")

    # Modifiers
    parts.append("<div class=\"cg-section\">")
    parts.append(f"<h3>Word modifiers ({len(data['modifiers'])})</h3>")
    parts.append("<p class=\"cg-meta\">Trailing <code>:X</code> modifiers applied to history words, "
                 "filename expansions, and parameter results.</p>")
    parts.append("<table class=\"cg-table\">")
    parts.append("  <thead><tr><th>Modifier</th><th>Meaning</th></tr></thead>")
    parts.append("  <tbody>")
    for e in data["modifiers"]:
        parts.append(f"    <tr><td><code>{h(e['sym'])}</code></td>"
                     f"<td>{h(e['doc'])}</td></tr>")
    parts.append("  </tbody>")
    parts.append("</table>")
    parts.append("</div>")

    parts.append(END_HTML)
    return "\n".join(parts)


# ── Driver ──────────────────────────────────────────────────────────
def replace_between(src: str, begin: str, end: str, body: str, where: str) -> str:
    if begin not in src or end not in src:
        raise SystemExit(f"markers not found in {where}: {begin!r} / {end!r}")
    pre, _, rest = src.partition(begin)
    _, _, post = rest.partition(end)
    return f"{pre}{body}{post}"


def main() -> None:
    data = json.loads(CANON.read_text(encoding="utf-8"))

    html_body = render_html(data)
    for f in HTML_FILES:
        src = f.read_text(encoding="utf-8")
        new = replace_between(src, BEGIN_HTML, END_HTML, html_body, str(f))
        if new != src:
            f.write_text(new, encoding="utf-8")
            print(f"updated {f}")
        else:
            print(f"{f} unchanged")


if __name__ == "__main__":
    main()
