/// `BUILD_VERSION` constant.
#![cfg_attr(all(nightly, feature = "benchmark"), feature(test))]
#![allow(non_camel_case_types)]
/// `BUILD_VERSION` constant.
pub const BUILD_VERSION: &str = env!("FISH_BUILD_VERSION");
/// `common` submodule.
#[macro_use]
pub mod common;
/// `wutil` submodule.
#[macro_use]
pub mod wutil;
/// `abbrs` submodule.
pub mod abbrs;
/// `ast` submodule.
pub mod ast;
/// `autoload` submodule.
pub mod autoload;
/// `builtins` submodule.
pub mod builtins;
/// `complete` submodule.
pub mod complete;
/// `editable_line` submodule.
pub mod editable_line;
/// `env` submodule.
pub mod env;
/// `env_dispatch` submodule.
pub mod env_dispatch;
/// `env_universal_common` submodule.
pub mod env_universal_common;
/// `event` submodule.
pub mod event;
/// `exec` submodule.
pub mod exec;
/// `expand` submodule.
pub mod expand;
/// `fd_monitor` submodule.
pub mod fd_monitor;
/// `fd_readable_set` submodule.
pub mod fd_readable_set;
/// `fds` submodule.
pub mod fds;
/// `flog` submodule.
pub mod flog;
/// `fork_exec` submodule.
pub mod fork_exec;
/// `fs` submodule.
pub mod fs;
/// `function` submodule.
pub mod function;
/// `global_safety` submodule.
pub mod global_safety;
/// `highlight` submodule.
pub mod highlight;
/// `history` submodule.
pub mod history;
/// `input` submodule.
pub mod input;
/// `input_common` submodule.
pub mod input_common;
/// `io` submodule.
pub mod io;
/// `job_group` submodule.
pub mod job_group;
/// `key` submodule.
pub mod key;
/// `kill` submodule.
pub mod kill;
/// `locale` submodule.
pub mod locale;
/// `localization` submodule.
pub mod localization;
/// `nix` submodule.
pub mod nix;
/// `null_terminated_array` submodule.
pub mod null_terminated_array;
/// `operation_context` submodule.
pub mod operation_context;
/// `pager` submodule.
pub mod pager;
/// `panic` submodule.
pub mod panic;
/// `parse_constants` submodule.
pub mod parse_constants;
/// `parse_execution` submodule.
pub mod parse_execution;
/// `parse_tree` submodule.
pub mod parse_tree;
/// `parse_util` submodule.
pub mod parse_util;
/// `parser` submodule.
pub mod parser;
/// `parser_keywords` submodule.
pub mod parser_keywords;
/// `path` submodule.
pub mod path;
/// `portable_atomic` submodule.
pub mod portable_atomic;
/// `prelude` submodule.
pub mod prelude;
/// `print_help` submodule.
pub mod print_help;
/// `proc` submodule.
pub mod proc;
/// `re` submodule.
pub mod re;
/// `reader` submodule.
pub mod reader;
/// `redirection` submodule.
pub mod redirection;
/// `screen` submodule.
pub mod screen;
/// `signal` submodule.
pub mod signal;
/// `stdx` submodule.
pub mod stdx;
/// `terminal` submodule.
pub mod terminal;
/// `termsize` submodule.
pub mod termsize;
/// `text_face` submodule.
pub mod text_face;
/// `threads` submodule.
pub mod threads;
/// `timer` submodule.
pub mod timer;
/// `tinyexpr` submodule.
pub mod tinyexpr;
/// `tokenizer` submodule.
pub mod tokenizer;
/// `topic_monitor` submodule.
pub mod topic_monitor;
/// `trace` submodule.
pub mod trace;
/// `tty_handoff` submodule.
pub mod tty_handoff;
/// `universal_notifier` submodule.
pub mod universal_notifier;
/// `wait_handle` submodule.
pub mod wait_handle;
/// `wildcard` submodule.
pub mod wildcard;

#[cfg(feature = "gettext-extract")]
pub extern crate fish_gettext_extraction;

#[cfg(test)]
mod tests;
