
# GENERATED by scripts/ztst_compsys.py --core-minimize; do not edit
#
# Reduced from upstream A01grammar#15
#   assertion #15: exclamation marks without following commands
#
# Run it against each shell and diff the two outputs:
#
#   /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh -f tests/ztst_compsys/repros_core/a01grammar_015.zsh /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh > /tmp/a.txt 2>&1
#   ZSHRS_NATIVE_ZLE_FX=0 /Users/wizard/RustroverProjects/zshrs/target/debug/zshrs -f tests/ztst_compsys/repros_core/a01grammar_015.zsh /Users/wizard/RustroverProjects/zshrs/target/debug/zshrs > /tmp/b.txt 2>&1
#   diff -u /tmp/a.txt /tmp/b.txt
#
# Derived from upstream's own A01grammar.ztst; that file is not modified.  The
# preamble reproduces the parts of Test/ztst.zsh a chunk can observe -- the
# module path (ztst.zsh:48-50), $fpath (ztst.zsh:112-114), zsh/parameter
# (ztst.zsh:54), the un-exported WORDCHARS (ztst.zsh:46) and the option state
# captured at ztst.zsh:59 -- and each chunk is replayed through the same
# anonymous-function wrapper ZTST_execchunk uses (ztst.zsh:301-305), so `local`
# scopes and "(eval):N:" error prefixes come out as they do in the suite.

emulate -R zsh
setopt extendedglob nonomatch
unset -m LC_\*
export LANG=C

build=/private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc
work=$(mktemp -d "${TMPDIR:-/tmp}/ztst_core_repro.XXXXXX")
# $2 is a ready-made module farm, passed by the reducer so that a hundred
# probes do not each re-glob the build tree and re-link 38 modules.  Standalone
# (no $2) the script builds its own, so the emitted repro stays self-contained.
if [[ -n $2 ]]; then
  module_path=( $2 )
else
  mkdir -p $work/Modules/zsh
  for so in $build/Src/**/*.so(N); do ln -sf $so $work/Modules/zsh; done
  module_path=( $work/Modules )
fi
ZTST_srcdir=$build/Test
# Several tests run "$ZTST_exe -fc ..." or "$ZTST_testdir/../Src/zsh"; in the
# suite both are the shell under test (Test/Makefile.in:56, and the Src/zsh
# symlink this runner stages next to the test directory), so the same layout
# has to exist here -- otherwise those tests fail on a missing path and the
# reduction anchors on the driver instead of on the bug.
ZTST_exe=${1:-$build/Src/zsh}
mkdir -p $work/Src $work/Test
ln -sf $ZTST_exe $work/Src/zsh
ZTST_testdir=$work/Test
cd $ZTST_testdir
fpath=( $ZTST_srcdir/../Functions/*~*/CVS(/)
        $ZTST_srcdir/../Completion
        $ZTST_srcdir/../Completion/*/*~*/CVS(/) )
zmodload zsh/parameter 2>/dev/null
typeset +x WORDCHARS
emulate -R zsh




() { eval '  fn() { ! {!} && ! (!) || ! {!} }' } </dev/null
print -ru2 -- "<<STATUS:$?>>"
cd /
rm -rf $work
