
# GENERATED by scripts/ztst_compsys.py --core-minimize; do not edit
#
# Reduced from upstream X04zlehighlight#2
#   assertion #2: basic region_highlight with 8 colors
#
# Run it against each shell and diff the two outputs:
#
#   /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh -f tests/ztst_compsys/repros_core/x04zlehighlight_002.zsh /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh > /tmp/a.txt 2>&1
#   ZSHRS_NATIVE_ZLE_FX=0 <shell-under-test> -f tests/ztst_compsys/repros_core/x04zlehighlight_002.zsh <shell-under-test> > /tmp/b.txt 2>&1
#   diff -u /tmp/a.txt /tmp/b.txt
#
# Derived from upstream's own X04zlehighlight.ztst; that file is not modified.  The
# preamble reproduces the parts of Test/ztst.zsh a chunk can observe -- the
# module path (ztst.zsh:48-50), $fpath (ztst.zsh:112-114), zsh/parameter
# (ztst.zsh:54), the un-exported WORDCHARS (ztst.zsh:46) and the option state
# captured at ztst.zsh:59 -- and each chunk is replayed through the same
# anonymous-function wrapper ZTST_execchunk uses (ztst.zsh:301-305), so `local`
# scopes and "(eval):N:" error prefixes come out as they do in the suite.

emulate -R zsh
setopt extendedglob nonomatch
unset -m LC_\*
export LANG=C

build=/private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc
work=$(mktemp -d "${TMPDIR:-/tmp}/ztst_core_repro.XXXXXX")
# $2 is a ready-made module farm, passed by the reducer so that a hundred
# probes do not each re-glob the build tree and re-link 38 modules.  Standalone
# (no $2) the script builds its own, so the emitted repro stays self-contained.
if [[ -n $2 ]]; then
  module_path=( $2 )
else
  mkdir -p $work/Modules/zsh
  for so in $build/Src/**/*.so(N); do ln -sf $so $work/Modules/zsh; done
  module_path=( $work/Modules )
fi
ZTST_srcdir=$build/Test
# Several tests run "$ZTST_exe -fc ..." or "$ZTST_testdir/../Src/zsh"; in the
# suite both are the shell under test (Test/Makefile.in:56, and the Src/zsh
# symlink this runner stages next to the test directory), so the same layout
# has to exist here -- otherwise those tests fail on a missing path and the
# reduction anchors on the driver instead of on the bug.
ZTST_exe=${1:-$build/Src/zsh}
mkdir -p $work/Src $work/Test
ln -sf $ZTST_exe $work/Src/zsh
ZTST_testdir=$work/Test
cd $ZTST_testdir
fpath=( $ZTST_srcdir/../Functions/*~*/CVS(/)
        $ZTST_srcdir/../Completion
        $ZTST_srcdir/../Completion/*/*~*/CVS(/) )
zmodload zsh/parameter 2>/dev/null
typeset +x WORDCHARS
emulate -R zsh

() { eval '  export TERM=xterm-256color' } </dev/null
print -ru2 -- "<<STATUS:$?>>"
() { eval '  if [[ ${+termcap} != 1 || ${termcap[Co]} != <-> || ${termcap[Co]} -lt 256 ]]; then
    ZTST_unimplemented="no termcap module OR termcap doesn'\''t support 256 or more colors"
  elif zmodload zsh/zpty 2> /dev/null; then
    zpty_start() {
      export PS1= PS2=
      zpty -d
      zpty zsh "${(q)ZTST_testdir}/../Src/zsh -fiV +Z"
      zpty -w zsh "module_path=( ${(j< >)${(@q-)module_path}} \$module_path )"
      zpty -w zsh '\''zle_highlight=( fg_start_code:"CDE|3" fg_end_code:"|" bg_start_code:"BCDE|4" bg_end_code:"|" )'\''
      zpty -w zsh '\''.term.extensions=( -query truecolor -bracketed-paste -integration )'\''
    }
    zpty_input() {
      zpty ${${(M)2:#nonl}:+-n} -w zsh "$1"
    }
    zpty_enable_zle() {
      zpty -w zsh "tcfunc() { REPLY=""; }"
      # This line will not be echoed back, behaving like ! -o zle
      zpty -w zsh "setopt zle; zle -T tc tcfunc"
    }
    zpty_line() {
      setopt localoptions extendedglob noshwordsplit
      local REPLY cm=$'\''\r'\''
      integer i
      for (( i = 0; i < ${1:-1}; ++i )); do
        zpty -r zsh REPLY
        # Normalise me/sgr0 to \e[0m. We also need to strip \e(B in zpty_stop()
        REPLY=${REPLY//${termcap[me]}/$'\''\x1b[0m'\''}
        # P is for "preserve", and induces keeping some
        # expected color codes to test region_highlight,
        # etc. - the color codes are made a regular text.
        [[ "$2" = "p" ]] && {
            REPLY=${REPLY//(#b)$'\''\x1b'\''\[([0-9;]##m)/${match[1]}}
        } || {
            REPLY=${REPLY//$'\''\x1b'\''\[[0-9;]##m/}   # remove all [0-9]...m codes
        }
        # Fix e^Mexit - match ((?)\r(?)), if \2 == \3, then replace with \2
        # otherwise replace with \1 stripped out of leading/trailing [[:space:]]
        REPLY=${REPLY//(#b)((?(#c0,1))$cm(?(#c0,1)))/${${${(M)match[2]:#${match[3]}}:+${match[2]}}:-${${match[1]##[[:space:]]##}%%[[:space:]]##}}}
        [[ -n "$REPLY" ]] && print -r -- ${${REPLY%%${~cm}*}##[[:space:]]##}
      done
    }
    zpty_stop() {
      setopt localoptions extendedglob
      local REPLY cm=$'\''\r'\''
      # To early Ctrl-D might happen, it was happening when debug
      # logs were writing to a file slowing down Zle a little
      LANG=C sleep 0.333
      # Zle is active, can use Ctrl-D to exit
      zpty -n -w zsh $'\''\C-d'\''
      # zpty gives no output when piped without these braces (?)
      # The while loop with // substitution is to convert `e^Mexit'\''
      # into `exit'\'' (see zpty_line). The sed commands remove escapes
      { zpty -r zsh } |
      sed -e $'\''/[^\t\r ]/!d'\'' -e $'\''s/\r$//'\'' -e $'\''s/\x1b\\[[0-9;]*m//g'\'' -e $'\''s/\x1b([A-Z]//g'\'' |
      while read REPLY; do
        REPLY=${REPLY//(#b)((?(#c0,1))$cm(?(#c0,1)))/${${${(M)match[2]:#${match[3]}}:+${match[2]}}:-${${match[1]##[[:space:]]##}%%[[:space:]]##}}}
        print -rn -- "$REPLY"
      done
      zpty -d
      :
    }
  else
    ZTST_unimplemented='\''the zsh/zpty module is not available'\''
  fi' } </dev/null
print -ru2 -- "<<STATUS:$?>>"


() { eval '  zpty_start
  zpty_input '\''rh_widget() { BUFFER="true"; region_highlight+=( "0 4 fg=green" ); }'\''
  zpty_input '\''zle -N rh_widget'\''
  zpty_input '\''bindkey "\C-a" rh_widget'\''
  zpty_enable_zle
  zpty_input $'\''\C-a'\''  # emits newline, which executes BUFFER="true" command
  zpty_line 1 p       # the line of interest, preserving escapes ("p")' } </dev/null
print -ru2 -- "<<STATUS:$?>>"
cd /
rm -rf $work
