# GENERATED by scripts/ztst_compsys.py --minimize; do not edit
#
# Reduced from upstream Y02compmatch#49
#   assertion #49: Non-bug from workers 11388
#
# Run it against each shell and diff the two outputs:
#
#   /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh -f tests/ztst_compsys/repros/y02compmatch_049.zsh /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc > /tmp/a.txt
#   ZSHRS_NATIVE_ZLE_FX=0 /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh -f tests/ztst_compsys/repros/y02compmatch_049.zsh /Users/wizard/RustroverProjects/zshrs/target/debug/zshrs /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc > /tmp/b.txt
#   diff -u /tmp/a.txt /tmp/b.txt
#
# Everything below is derived from upstream's own Y02compmatch and
# Test/comptest.  Neither upstream file is modified; this script only replays
# the reduced setup through the unmodified comptestinit/comptest driver.

emulate -R zsh
setopt extendedglob
# zsh/zpty is loaded by comptestinit, after it has pointed module_path at the
# build tree; loading it here would look in the install prefix and fail.

sut=${1:?usage: <harness-zsh> -f $0 <shell-under-test> [<built-zsh-tree>]}
build=${2:-/private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc}
[[ -x $build/Src/zsh && -r $build/Test/comptest ]] || {
  print -u2 "$0: not a built zsh source tree: $build"
  exit 2
}

ZTST_srcdir=$build/Test
ZTST_verbose=0
ZTST_fd=2



work=$(mktemp -d "${TMPDIR:-/tmp}/ztst_repro.XXXXXX")
mkdir -p $work/Modules/zsh
for so in $build/Src/**/*.so(N); do ln -sf $so $work/Modules/zsh; done
ZTST_testdir=$work
mkdir $work/comp.tmp
cd $work/comp.tmp
. $ZTST_srcdir/comptest

comptestinit -z $sut || exit 1
      test_code () {
    	matcher=$1;
    	list=$2;
    	code="compdef _tst tst ; _tst () { echo -n '<COMPADD>';compadd -M '"
    	code="$code$matcher"
    	code="$code'  - ${(P)list} ; echo  -n '</COMPADD>'"
          code="$code; $extra_cmd"
          code="$code; echo -n '<INSERT_POSITIONS>'"
          code="$code; echo \$compstate[insert_positions]"
          code="$code; echo -n '</INSERT_POSITIONS>'"
          code="$code}"
    	comptesteval "$code"
      }
 workers_11388_matcher='r:|[:.]=* r:|=*'
 workers_11388_list=(a.b:0 c.d:1)
 test_code $workers_11388_matcher workers_11388_list
 comptest $'tst :\t'

 workers_11388_matcher='r:|[:.]=** r:|=*'
 test_code $workers_11388_matcher workers_11388_list
 comptest $'tst :\t'
zpty -d zsh 2>/dev/null
cd /
rm -rf $work
