# GENERATED by scripts/ztst_compsys.py --minimize; do not edit
#
# Reduced from upstream Y04regexargs#3
#   assertion #3: optional fields after a suffix
#
# Run it against each shell and diff the two outputs:
#
#   /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh -f tests/ztst_compsys/repros/y04regexargs_003.zsh /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc > /tmp/a.txt
#   ZSHRS_NATIVE_ZLE_FX=0 /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc/Src/zsh -f tests/ztst_compsys/repros/y04regexargs_003.zsh /Users/wizard/RustroverProjects/zshrs/target/debug/zshrs /private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc > /tmp/b.txt
#   diff -u /tmp/a.txt /tmp/b.txt
#
# Everything below is derived from upstream's own Y04regexargs and
# Test/comptest.  Neither upstream file is modified; this script only replays
# the reduced setup through the unmodified comptestinit/comptest driver.

emulate -R zsh
setopt extendedglob
# zsh/zpty is loaded by comptestinit, after it has pointed module_path at the
# build tree; loading it here would look in the install prefix and fail.

sut=${1:?usage: <harness-zsh> -f $0 <shell-under-test> [<built-zsh-tree>]}
build=${2:-/private/tmp/claude-501/-Users-wizard-RustroverProjects-zshrs/5152e3c4-dbb3-47e6-bcca-262529ff281e/scratchpad/zshsrc}
[[ -x $build/Src/zsh && -r $build/Test/comptest ]] || {
  print -u2 "$0: not a built zsh source tree: $build"
  exit 2
}

ZTST_srcdir=$build/Test
ZTST_verbose=0
ZTST_fd=2



work=$(mktemp -d "${TMPDIR:-/tmp}/ztst_repro.XXXXXX")
mkdir -p $work/Modules/zsh
for so in $build/Src/**/*.so(N); do ln -sf $so $work/Modules/zsh; done
ZTST_testdir=$work
mkdir $work/comp.tmp
cd $work/comp.tmp
. $ZTST_srcdir/comptest

comptestinit -z $sut || exit 1
      word=$'[^\0]#\0'
      comptesteval \
        'compdef _tst tst' \
	'setopt extended_glob' # running _regex_arguments outside of completion below
      tst_regex() { comptesteval "_regex_arguments _tst /$'[^\0]#\0'/ ${${(@q)*}}" }


 tst_regex /$'rpc\0'/ \
   \(\
     /"$word"/ ':programs:program:compadd -qS, mountd nisd' \
   \|\
     /$'[^,\0]##,[^,\0]##,'/ /$'[^,\0]##\0'/ ':procedures:procedure:' \
   \|\
     /$'[^,\0]##,'/ /$'[^,\0]##\0'/ ':versions:version:' \
   \)
  comptest $'tst rpc m\t\t'
zpty -d zsh 2>/dev/null
cd /
rm -rf $work
